org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
android.defaults.buildfeatures.resvalues=true
android.uniquePackageNames=false
android.dependency.useConstraints=true
android.newDsl=false
android.builtInKotlin=false
android.generateSyncIssueWhenLibraryConstraintsAreEnabled=false
