package app.tijario.config

import androidx.compose.runtime.Composable
import androidx.compose.runtime.compositionLocalOf

enum class AppLanguage { AR, EN }

val LocalLanguage = compositionLocalOf { AppLanguage.AR }

object Localization {
    private val translations = mapOf(
        "app_name" to mapOf(AppLanguage.AR to "تجاريو", AppLanguage.EN to "Tijario"),
        "app_slogan" to mapOf(AppLanguage.AR to "أدر تجارتك وفواتيرك بذكاء وسرعة", AppLanguage.EN to "Manage your business and invoices smartly"),

        // Navigation / Tabs
        "tab_home" to mapOf(AppLanguage.AR to "الرئيسية", AppLanguage.EN to "Home"),
        "tab_customers" to mapOf(AppLanguage.AR to "العملاء", AppLanguage.EN to "Customers"),
        "tab_products" to mapOf(AppLanguage.AR to "المنتجات", AppLanguage.EN to "Products"),
        "tab_documents" to mapOf(AppLanguage.AR to "المستندات", AppLanguage.EN to "Documents"),
        "tab_ai" to mapOf(AppLanguage.AR to "تجاريو AI", AppLanguage.EN to "Tijario AI"),
        "tab_account" to mapOf(AppLanguage.AR to "الحساب", AppLanguage.EN to "Account"),

        // Login Screen
        "login_title" to mapOf(AppLanguage.AR to "تسجيل الدخول", AppLanguage.EN to "Login"),
        "login_subtitle" to mapOf(AppLanguage.AR to "ادخل إلى حساب تجاري لمتابعة إدارة متجرك.", AppLanguage.EN to "Sign in to manage your store and invoices."),
        "email" to mapOf(AppLanguage.AR to "البريد الإلكتروني", AppLanguage.EN to "Email"),
        "password" to mapOf(AppLanguage.AR to "كلمة المرور", AppLanguage.EN to "Password"),
        "forgot_password" to mapOf(AppLanguage.AR to "نسيت كلمة المرور؟", AppLanguage.EN to "Forgot Password?"),
        "btn_login" to mapOf(AppLanguage.AR to "دخول", AppLanguage.EN to "Login"),
        "or" to mapOf(AppLanguage.AR to "أو", AppLanguage.EN to "Or"),
        "google_login" to mapOf(AppLanguage.AR to "تسجيل الدخول باستخدام Google", AppLanguage.EN to "Sign in with Google"),
        "google_register" to mapOf(AppLanguage.AR to "التسجيل باستخدام Google", AppLanguage.EN to "Sign up with Google"),
        "no_account" to mapOf(AppLanguage.AR to "ليس لديك حساب؟ ", AppLanguage.EN to "Don't have an account? "),
        "create_account" to mapOf(AppLanguage.AR to "أنشئ حساباً جديداً", AppLanguage.EN to "Create an account"),

        // Register Screen
        "register_title" to mapOf(AppLanguage.AR to "إنشاء حساب جديد", AppLanguage.EN to "Register"),
        "register_subtitle" to mapOf(AppLanguage.AR to "انضم إلى تجاريو وابدأ في تنظيم أعمالك اليوم", AppLanguage.EN to "Join Tijario and organize your business today"),
        "fullname" to mapOf(AppLanguage.AR to "الاسم الكامل", AppLanguage.EN to "Full Name"),
        "already_have_account" to mapOf(AppLanguage.AR to "لديك حساب بالفعل؟ ", AppLanguage.EN to "Already have an account? "),

        // Forgot Password
        "reset_password_title" to mapOf(AppLanguage.AR to "استعادة كلمة المرور", AppLanguage.EN to "Reset Password"),
        "reset_password_subtitle" to mapOf(AppLanguage.AR to "سنرسل لك رابطاً لإعادة تعيين كلمة المرور", AppLanguage.EN to "We will send you a reset link to your email"),
        "btn_send_reset" to mapOf(AppLanguage.AR to "إرسال رابط الاستعادة", AppLanguage.EN to "Send Reset Link"),
        "back_to_login" to mapOf(AppLanguage.AR to "العودة لتسجيل الدخول", AppLanguage.EN to "Back to Login"),
        "reset_success" to mapOf(AppLanguage.AR to "تم إرسال رابط استعادة كلمة المرور بنجاح إلى بريدك الإلكتروني.", AppLanguage.EN to "Reset link has been successfully sent to your email."),

        // Onboarding / Shop Setup
        "onboarding_title" to mapOf(AppLanguage.AR to "تهيئة حساب متجرك", AppLanguage.EN to "Setup Your Store"),
        "onboarding_subtitle" to mapOf(AppLanguage.AR to "أدخل بيانات نشاطك التجاري لبدء إصدار الفواتير", AppLanguage.EN to "Enter business details to start issuing documents"),
        "shop_name" to mapOf(AppLanguage.AR to "اسم المتجر / النشاط التجاري", AppLanguage.EN to "Store / Business Name"),
        "whatsapp_phone" to mapOf(AppLanguage.AR to "رقم واتساب للتواصل", AppLanguage.EN to "WhatsApp Phone Number"),
        "country" to mapOf(AppLanguage.AR to "الدولة", AppLanguage.EN to "Country"),
        "currency" to mapOf(AppLanguage.AR to "العملة", AppLanguage.EN to "Currency"),
        "btn_save_continue" to mapOf(AppLanguage.AR to "حفظ وإكمال الإعداد", AppLanguage.EN to "Save & Continue"),

        // Dashboard
        "welcome" to mapOf(AppLanguage.AR to "أهلاً بك في تجاريو 👋", AppLanguage.EN to "Welcome to Tijario 👋"),
        "dash_subtitle" to mapOf(AppLanguage.AR to "متابعة سريعة لأداء عملك التجاري اليوم", AppLanguage.EN to "Quick overview of your business performance"),
        "financial_summary" to mapOf(AppLanguage.AR to "الملخص المالي العام", AppLanguage.EN to "Financial Summary"),
        "this_month" to mapOf(AppLanguage.AR to "هذا الشهر", AppLanguage.EN to "This Month"),
        "paid_invoices" to mapOf(AppLanguage.AR to "الفواتير المدفوعة", AppLanguage.EN to "Paid Invoices"),
        "pending_quotes" to mapOf(AppLanguage.AR to "عروض الأسعار المعلقة", AppLanguage.EN to "Pending Quotes"),
        "quick_actions" to mapOf(AppLanguage.AR to "إجراءات سريعة", AppLanguage.EN to "Quick Actions"),
        "btn_new_invoice" to mapOf(AppLanguage.AR to "فاتورة جديدة", AppLanguage.EN to "New Invoice"),
        "btn_new_quote" to mapOf(AppLanguage.AR to "عرض سعر جديد", AppLanguage.EN to "New Quote"),
        "btn_add_customer" to mapOf(AppLanguage.AR to "إضافة عميل", AppLanguage.EN to "Add Customer"),

        // Customers Screen
        "customers_title" to mapOf(AppLanguage.AR to "العملاء", AppLanguage.EN to "Customers"),
        "customers_subtitle" to mapOf(AppLanguage.AR to "سجل العملاء وإدارة الحسابات المسجلة", AppLanguage.EN to "Customer registry and registered accounts"),
        "search_placeholder" to mapOf(AppLanguage.AR to "البحث عن عميل...", AppLanguage.EN to "Search for a customer..."),

        // Documents Screen
        "documents_title" to mapOf(AppLanguage.AR to "المستندات", AppLanguage.EN to "Documents"),
        "documents_subtitle" to mapOf(AppLanguage.AR to "استعراض وإدارة جميع فواتيرك وعروض الأسعار", AppLanguage.EN to "View and manage all your invoices and quotes"),
        "doc_status_paid" to mapOf(AppLanguage.AR to "مدفوعة", AppLanguage.EN to "Paid"),
        "doc_status_draft" to mapOf(AppLanguage.AR to "مسودة", AppLanguage.EN to "Draft"),
        "doc_status_expired" to mapOf(AppLanguage.AR to "منتهية", AppLanguage.EN to "Expired"),
        "section_invoices" to mapOf(AppLanguage.AR to "قسم الفواتير", AppLanguage.EN to "Invoices Section"),
        "section_quotes" to mapOf(AppLanguage.AR to "قسم عروض الأسعار", AppLanguage.EN to "Quotes Section"),
        "btn_create_invoice" to mapOf(AppLanguage.AR to "إنشاء فاتورة جديدة", AppLanguage.EN to "Create New Invoice"),
        "btn_create_quote" to mapOf(AppLanguage.AR to "إنشاء عرض سعر جديد", AppLanguage.EN to "Create New Quote"),

        // AI Tools Screen
        "ai_title" to mapOf(AppLanguage.AR to "مساعد تجاريو الذكي (AI)", AppLanguage.EN to "Tijario AI Assistant"),
        "ai_subtitle" to mapOf(AppLanguage.AR to "صياغة ردود العملاء وكتابة الأوصاف لمنتجاتك بلمح البصر", AppLanguage.EN to "Draft replies and write product captions in a flash"),
        "ai_card_title" to mapOf(AppLanguage.AR to "صياغة رد ذكي للعملاء", AppLanguage.EN to "Draft Smart Reply"),
        "ai_input_placeholder" to mapOf(AppLanguage.AR to "الصق رسالة العميل هنا...", AppLanguage.EN to "Paste client message here..."),
        "btn_generate_reply" to mapOf(AppLanguage.AR to "توليد الرد الذكي", AppLanguage.EN to "Generate Smart Reply"),
        "ai_suggestion" to mapOf(AppLanguage.AR to "الرد المقترح:", AppLanguage.EN to "Suggested Reply:"),
        "tab_ai_reply" to mapOf(AppLanguage.AR to "رد ذكي", AppLanguage.EN to "Smart Reply"),
        "tab_ai_caption" to mapOf(AppLanguage.AR to "كابشن ذكي", AppLanguage.EN to "Smart Caption"),
        "ai_caption_card_title" to mapOf(AppLanguage.AR to "كتابة كابشن ذكي للمنتجات", AppLanguage.EN to "Generate Smart Caption"),
        "ai_caption_input_placeholder" to mapOf(AppLanguage.AR to "اكتب تفاصيل أو مميزات المنتج هنا...", AppLanguage.EN to "Type product details or features here..."),
        "btn_generate_caption" to mapOf(AppLanguage.AR to "توليد الكابشن الذكي", AppLanguage.EN to "Generate Smart Caption"),
        "ai_caption_suggestion" to mapOf(AppLanguage.AR to "الكابشن المقترح:", AppLanguage.EN to "Suggested Caption:"),

        // Account Screen
        "account_title" to mapOf(AppLanguage.AR to "الحساب والاستخدام", AppLanguage.EN to "Account & Usage"),
        "settings_lang" to mapOf(AppLanguage.AR to "لغة التطبيق", AppLanguage.EN to "App Language"),
        "settings_theme" to mapOf(AppLanguage.AR to "مظهر التطبيق (Theme)", AppLanguage.EN to "App Theme"),
        "theme_light" to mapOf(AppLanguage.AR to "فاتح", AppLanguage.EN to "Light"),
        "theme_dark" to mapOf(AppLanguage.AR to "داكن", AppLanguage.EN to "Dark"),
        "account_pro_badge" to mapOf(AppLanguage.AR to "الباقة الاحترافية (Pro)", AppLanguage.EN to "Pro Plan"),
        "monthly_limits" to mapOf(AppLanguage.AR to "الاستهلاك والحدود الشهرية", AppLanguage.EN to "Monthly Limits & Usage"),
        "limit_docs" to mapOf(AppLanguage.AR to "عروض الأسعار والفواتير المتبقية", AppLanguage.EN to "Remaining Quotes & Invoices"),
        "limit_ai" to mapOf(AppLanguage.AR to "عمليات الذكاء الاصطناعي (AI)", AppLanguage.EN to "AI Operations"),
        "store_premium" to mapOf(AppLanguage.AR to "متجر تجاريو الفاخر", AppLanguage.EN to "Tijario Premium Store"),

        // Form Screens
        "form_client_info" to mapOf(AppLanguage.AR to "بيانات العميل المستهدف", AppLanguage.EN to "Target Customer Details"),
        "form_items_info" to mapOf(AppLanguage.AR to "تفاصيل البنود والأسعار", AppLanguage.EN to "Items & Pricing Details"),
        "form_item_name" to mapOf(AppLanguage.AR to "اسم البند / الخدمة", AppLanguage.EN to "Item / Service Name"),
        "form_quantity" to mapOf(AppLanguage.AR to "الكمية", AppLanguage.EN to "Quantity"),
        "form_unit_price" to mapOf(AppLanguage.AR to "سعر الوحدة", AppLanguage.EN to "Unit Price"),
        "form_discount" to mapOf(AppLanguage.AR to "الخصم", AppLanguage.EN to "Discount"),
        "form_extra_fees" to mapOf(AppLanguage.AR to "رسوم إضافية", AppLanguage.EN to "Extra Fees"),
        "btn_save_doc" to mapOf(AppLanguage.AR to "توليد وحفظ المستند", AppLanguage.EN to "Generate & Save Document"),
        "btn_save_customer" to mapOf(AppLanguage.AR to "حفظ بيانات العميل", AppLanguage.EN to "Save Customer Data"),
        "btn_save_settings" to mapOf(AppLanguage.AR to "حفظ التغييرات", AppLanguage.EN to "Save Changes"),
        "city" to mapOf(AppLanguage.AR to "المدينة", AppLanguage.EN to "City"),
        "notes" to mapOf(AppLanguage.AR to "ملاحظات إضافية", AppLanguage.EN to "Additional Notes"),
        "terms" to mapOf(AppLanguage.AR to "الشروط والأحكام الافتراضية للفواتير", AppLanguage.EN to "Default Invoice Terms"),
        "btn_back" to mapOf(AppLanguage.AR to "رجوع", AppLanguage.EN to "Back"),
        "config_req" to mapOf(AppLanguage.AR to "إعدادات الاتصال مطلوبة", AppLanguage.EN to "Connection Settings Required"),

        // Products & Services Screen
        "products_title" to mapOf(AppLanguage.AR to "المنتجات والخدمات", AppLanguage.EN to "Products & Services"),
        "products_subtitle" to mapOf(AppLanguage.AR to "إدارة مخزون منتجاتك والخدمات التي تقدمها", AppLanguage.EN to "Manage inventory of your products and services"),
        "search_products" to mapOf(AppLanguage.AR to "البحث عن منتج أو خدمة...", AppLanguage.EN to "Search for a product or service..."),
        "btn_add_product" to mapOf(AppLanguage.AR to "إضافة منتج أو خدمة", AppLanguage.EN to "Add Product/Service"),
        "product_name" to mapOf(AppLanguage.AR to "اسم المنتج / الخدمة", AppLanguage.EN to "Product/Service Name"),
        "product_description" to mapOf(AppLanguage.AR to "الوصف", AppLanguage.EN to "Description"),
        "product_price" to mapOf(AppLanguage.AR to "السعر", AppLanguage.EN to "Price"),
        "product_kind" to mapOf(AppLanguage.AR to "النوع", AppLanguage.EN to "Type"),
        "kind_product" to mapOf(AppLanguage.AR to "منتج", AppLanguage.EN to "Product"),
        "kind_service" to mapOf(AppLanguage.AR to "خدمة", AppLanguage.EN to "Service"),
        "btn_save_product" to mapOf(AppLanguage.AR to "حفظ المنتج/الخدمة", AppLanguage.EN to "Save Product/Service"),
        "config_req_msg" to mapOf(AppLanguage.AR to "الرجاء ضبط إعدادات Supabase في gradle.properties وتشغيل الخادم أو التحقق من الاتصال.", AppLanguage.EN to "Please configure Supabase settings in gradle.properties and start the server or verify connection."),
        "limit_reached_title" to mapOf(AppLanguage.AR to "تم الوصول للحد الأقصى", AppLanguage.EN to "Limit Reached"),
        "limit_reached_msg" to mapOf(AppLanguage.AR to "لقد استهلكت كامل الحد المسموح به من المستندات المتاحة لحسابك، يرجى الترقية للحصول على حد أكبر.", AppLanguage.EN to "You have consumed all allowed documents for your account. Please upgrade to get a higher limit."),
        "btn_ok" to mapOf(AppLanguage.AR to "حسناً", AppLanguage.EN to "OK"),
        "uncollected_amounts" to mapOf(AppLanguage.AR to "المبالغ غير المحصلة", AppLanguage.EN to "Uncollected Amounts"),
        "open_quotes" to mapOf(AppLanguage.AR to "العروض المفتوحة", AppLanguage.EN to "Open Quotes"),
        "new_invoice" to mapOf(AppLanguage.AR to "فاتورة جديدة", AppLanguage.EN to "New Invoice"),
        "new_quote" to mapOf(AppLanguage.AR to "عرض سعر جديد", AppLanguage.EN to "New Quote"),
        "add_customer" to mapOf(AppLanguage.AR to "إضافة عميل", AppLanguage.EN to "Add Customer"),
        "new_product_service" to mapOf(AppLanguage.AR to "إضافة منتج أو خدمة", AppLanguage.EN to "Add Product/Service"),
        "ai_assistant_sub" to mapOf(AppLanguage.AR to "مساعدك الذكي لأعمالك", AppLanguage.EN to "Your smart business assistant"),
        "no_docs_yet" to mapOf(AppLanguage.AR to "لا توجد فواتير أو عروض أسعار حتى الآن", AppLanguage.EN to "No invoices or quotes yet"),
        "unknown_customer" to mapOf(AppLanguage.AR to "عميل غير معروف", AppLanguage.EN to "Unknown Customer"),
        "confirm_delete" to mapOf(AppLanguage.AR to "تأكيد الحذف", AppLanguage.EN to "Confirm Delete"),
        "delete_customer_confirm" to mapOf(AppLanguage.AR to "هل أنت متأكد من رغبتك في حذف العميل؟", AppLanguage.EN to "Are you sure you want to delete this customer?"),
        "delete_customer_error" to mapOf(AppLanguage.AR to "تعذر حذف العميل.", AppLanguage.EN to "Could not delete customer."),
        "delete" to mapOf(AppLanguage.AR to "حذف", AppLanguage.EN to "Delete"),
        "cancel" to mapOf(AppLanguage.AR to "إلغاء", AppLanguage.EN to "Cancel"),
        "choose_customer_issue" to mapOf(AppLanguage.AR to "اختر العميل المُراد إصدار الفاتورة له", AppLanguage.EN to "Choose the target customer to issue document to"),
        "no_search_results" to mapOf(AppLanguage.AR to "لا يوجد نتائج تطابق البحث", AppLanguage.EN to "No results match search"),
        "add_new_customer" to mapOf(AppLanguage.AR to "إضافة عميل جديد", AppLanguage.EN to "Add New Customer"),
        "cant_open_whatsapp" to mapOf(AppLanguage.AR to "تعذر فتح تطبيق واتساب", AppLanguage.EN to "Could not open WhatsApp"),
        "delete_product_confirm" to mapOf(AppLanguage.AR to "هل أنت متأكد من رغبتك في حذف هذا البند؟", AppLanguage.EN to "Are you sure you want to delete this item?"),
        "delete_product_error" to mapOf(AppLanguage.AR to "تعذر حذف البند.", AppLanguage.EN to "Could not delete item."),
        "choose_product_doc" to mapOf(AppLanguage.AR to "اختر منتجًا أو خدمة لإضافتها للمستند", AppLanguage.EN to "Select a product or service to add to the document"),
        "no_products_available" to mapOf(AppLanguage.AR to "لا توجد منتجات أو خدمات متوفرة", AppLanguage.EN to "No products or services available"),
        "add_new_product" to mapOf(AppLanguage.AR to "إضافة بند جديد", AppLanguage.EN to "Add New Item"),
        "available_stock" to mapOf(AppLanguage.AR to "الكمية المتاحة: ", AppLanguage.EN to "Available stock: "),
        "cant_delete_doc" to mapOf(AppLanguage.AR to "تعذر حذف المستند حالياً", AppLanguage.EN to "Could not delete document currently"),
        "filter_all" to mapOf(AppLanguage.AR to "الكل", AppLanguage.EN to "All"),
        "filter_unpaid" to mapOf(AppLanguage.AR to "غير مدفوعة", AppLanguage.EN to "Unpaid"),
        "customer_active" to mapOf(AppLanguage.AR to "نشط", AppLanguage.EN to "Active"),
        "filter_paid" to mapOf(AppLanguage.AR to "مدفوعة", AppLanguage.EN to "Paid"),
        "filter_partial" to mapOf(AppLanguage.AR to "جزئية", AppLanguage.EN to "Partial"),
        "filter_latest" to mapOf(AppLanguage.AR to "الأحدث", AppLanguage.EN to "Latest"),
        "delete_doc_title" to mapOf(AppLanguage.AR to "حذف المستند", AppLanguage.EN to "Delete Document"),
        "delete_doc_confirm" to mapOf(AppLanguage.AR to "هل تريد حذف هذا المستند؟ لا يمكن التراجع عن هذا الإجراء.", AppLanguage.EN to "Do you want to delete this document? This action cannot be undone."),
        "edit_customer" to mapOf(AppLanguage.AR to "تعديل العميل", AppLanguage.EN to "Edit Customer"),
        "save_customer_error" to mapOf(AppLanguage.AR to "تعذر حفظ العميل. تحقق من البيانات وحاول مرة أخرى.", AppLanguage.EN to "Could not save customer. Check data and try again."),
        "edit_product" to mapOf(AppLanguage.AR to "تعديل البند", AppLanguage.EN to "Edit Item"),
        "save_product_error" to mapOf(AppLanguage.AR to "تعذر حفظ المنتج أو الخدمة. تحقق من البيانات وحاول مرة أخرى.", AppLanguage.EN to "Could not save product or service. Check data and try again."),
        "save_settings_error" to mapOf(AppLanguage.AR to "تعذر حفظ إعدادات المتجر. حاول مرة أخرى.", AppLanguage.EN to "Could not save business settings. Try again."),
        "settings" to mapOf(AppLanguage.AR to "الإعدادات", AppLanguage.EN to "Settings"),
        "invoice_notes" to mapOf(AppLanguage.AR to "ملاحظات إضافية", AppLanguage.EN to "Additional Notes"),
        
        // AI dialects, platforms, tones
        "ai_inquiry" to mapOf(AppLanguage.AR to "استفسار", AppLanguage.EN to "Inquiry"),
        "ai_objection" to mapOf(AppLanguage.AR to "اعتراض", AppLanguage.EN to "Objection"),
        "ai_greeting" to mapOf(AppLanguage.AR to "ترحيب", AppLanguage.EN to "Greeting"),
        "ai_gulf" to mapOf(AppLanguage.AR to "خليجية", AppLanguage.EN to "Gulf"),
        "ai_yemeni" to mapOf(AppLanguage.AR to "يمني", AppLanguage.EN to "Yemeni"),
        "ai_fusha_simple" to mapOf(AppLanguage.AR to "فصحى بسيطة", AppLanguage.EN to "Simple MSA"),
        "ai_egyptian" to mapOf(AppLanguage.AR to "مصرية", AppLanguage.EN to "Egyptian"),
        "ai_standard" to mapOf(AppLanguage.AR to "فصحى", AppLanguage.EN to "Standard"),
        "ai_notes_label" to mapOf(AppLanguage.AR to "ملاحظات إضافية أو معلومات وتفاصيل", AppLanguage.EN to "Additional notes or details"),
        "ai_instagram" to mapOf(AppLanguage.AR to "إنستغرام", AppLanguage.EN to "Instagram"),
        "ai_twitter" to mapOf(AppLanguage.AR to "تويتر", AppLanguage.EN to "Twitter"),
        "ai_facebook" to mapOf(AppLanguage.AR to "فيسبوك", AppLanguage.EN to "Facebook"),
        "ai_offer_label" to mapOf(AppLanguage.AR to "العرض الخاص (اختياري)", AppLanguage.EN to "Special offer (optional)"),
        "ai_notes_simple" to mapOf(AppLanguage.AR to "ملاحظات إضافية", AppLanguage.EN to "Additional notes"),
        "ai_reply_settings" to mapOf(AppLanguage.AR to "إعدادات الرد الذكي", AppLanguage.EN to "Smart Reply Settings"),
        "ai_caption_settings" to mapOf(AppLanguage.AR to "إعدادات كابشن منصات التواصل", AppLanguage.EN to "Social Media Caption Settings"),
        "ai_case_type" to mapOf(AppLanguage.AR to "نوع الحالة", AppLanguage.EN to "Case Type"),
        "ai_dialect" to mapOf(AppLanguage.AR to "اللهجة", AppLanguage.EN to "Dialect"),
        "ai_tone" to mapOf(AppLanguage.AR to "الأسلوب", AppLanguage.EN to "Tone"),
        "ai_platform" to mapOf(AppLanguage.AR to "المنصة", AppLanguage.EN to "Platform"),
        "ai_case_price_request" to mapOf(AppLanguage.AR to "طلب سعر", AppLanguage.EN to "Price request"),
        "ai_case_price_objection" to mapOf(AppLanguage.AR to "السعر غالي", AppLanguage.EN to "Price objection"),
        "ai_case_discount_request" to mapOf(AppLanguage.AR to "يريد خصم", AppLanguage.EN to "Discount request"),
        "ai_case_delivery_question" to mapOf(AppLanguage.AR to "سؤال عن التوصيل", AppLanguage.EN to "Delivery question"),
        "ai_case_availability_question" to mapOf(AppLanguage.AR to "سؤال عن التوفر", AppLanguage.EN to "Availability question"),
        "ai_case_customer_hesitant" to mapOf(AppLanguage.AR to "عميل متردد", AppLanguage.EN to "Hesitant customer"),
        "ai_case_customer_interested" to mapOf(AppLanguage.AR to "عميل مهتم", AppLanguage.EN to "Interested customer"),
        "ai_case_follow_up" to mapOf(AppLanguage.AR to "متابعة عميل", AppLanguage.EN to "Follow up"),
        "ai_case_payment_reminder" to mapOf(AppLanguage.AR to "تذكير بالدفع", AppLanguage.EN to "Payment reminder"),
        "ai_case_delayed_apology" to mapOf(AppLanguage.AR to "اعتذار عن التأخر", AppLanguage.EN to "Delayed response apology"),
        "ai_case_review_request" to mapOf(AppLanguage.AR to "طلب تقييم", AppLanguage.EN to "Review request"),
        "ai_case_general_inquiry" to mapOf(AppLanguage.AR to "استفسار عام", AppLanguage.EN to "General inquiry"),
        "ai_tone_premium" to mapOf(AppLanguage.AR to "فاخر", AppLanguage.EN to "Premium"),
        "ai_case_price_request_label" to mapOf(AppLanguage.AR to "طلب سعر", AppLanguage.EN to "Price request"),
        "ai_tone_label" to mapOf(AppLanguage.AR to "الأسلوب", AppLanguage.EN to "Tone"),
        "ai_audience_label" to mapOf(AppLanguage.AR to "نوع الجمهور", AppLanguage.EN to "Audience type"),
        "ai_settings_reply_title" to mapOf(AppLanguage.AR to "إعدادات الرد الذكي", AppLanguage.EN to "Smart Reply Settings"),
        "ai_settings_caption_title" to mapOf(AppLanguage.AR to "إعدادات الكابشن الذكي", AppLanguage.EN to "Smart Caption Settings"),
        "ai_reply_preview_title" to mapOf(AppLanguage.AR to "معاينة الرد", AppLanguage.EN to "Reply Preview"),
        "ai_caption_preview_title" to mapOf(AppLanguage.AR to "معاينة الكابشن", AppLanguage.EN to "Caption Preview"),
        "ai_report" to mapOf(AppLanguage.AR to "الإبلاغ عن هذا المحتوى", AppLanguage.EN to "Report this content"),
        "privacy_policy" to mapOf(AppLanguage.AR to "سياسة الخصوصية", AppLanguage.EN to "Privacy Policy"),
        "delete_account_web" to mapOf(AppLanguage.AR to "طلب حذف الحساب (ويب)", AppLanguage.EN to "Request Account Deletion (Web)"),
        "ai_cust_name_opt" to mapOf(AppLanguage.AR to "اسم العميل (اختياري)", AppLanguage.EN to "Customer name (optional)"),
        "ai_cust_msg_opt" to mapOf(AppLanguage.AR to "رسالة الزبون (اختياري)", AppLanguage.EN to "Customer message (optional)"),
        "ai_prod_srv_label" to mapOf(AppLanguage.AR to "المنتج أو الخدمة", AppLanguage.EN to "Product or Service"),
        "ai_add_image_opt" to mapOf(AppLanguage.AR to "إضافة صورة المنتج (اختياري)", AppLanguage.EN to "Add product image (optional)"),
        "ai_selected_image" to mapOf(AppLanguage.AR to "تم اختيار صورة المنتج", AppLanguage.EN to "Product image selected"),
        "ai_image_read_error" to mapOf(AppLanguage.AR to "تعذر قراءة صورة المنتج.", AppLanguage.EN to "Could not read the product image."),
        "ai_limit_reached" to mapOf(AppLanguage.AR to "لقد استهلكت كامل الحد المتاح لك من استعلامات الذكاء الاصطناعي لشهرك الحالي. يرجى الترقية للاستمرار.", AppLanguage.EN to "You have used all available AI requests for this month. Please upgrade to continue."),
        "ai_remove_image" to mapOf(AppLanguage.AR to "إزالة الصورة", AppLanguage.EN to "Remove image"),
        "ai_btn_gen_caption" to mapOf(AppLanguage.AR to "توليد الكابشن", AppLanguage.EN to "Generate Caption"),
        "ai_tone_friendly" to mapOf(AppLanguage.AR to "ودي", AppLanguage.EN to "Friendly"),
        "ai_tone_formal" to mapOf(AppLanguage.AR to "رسمي", AppLanguage.EN to "Formal"),
        "ai_tone_sales" to mapOf(AppLanguage.AR to "تسويقي", AppLanguage.EN to "Sales"),
        "ai_tone_funny" to mapOf(AppLanguage.AR to "مرح", AppLanguage.EN to "Funny"),
        "complete_settings_logo" to mapOf(AppLanguage.AR to "أكمل إعدادات المتجر أولاً قبل رفع الشعار", AppLanguage.EN to "Please complete store settings first before uploading logo"),
        "logo_saved_success" to mapOf(AppLanguage.AR to "تم حفظ شعار المتجر بنجاح", AppLanguage.EN to "Store logo saved successfully"),
        "logo_upload_error" to mapOf(AppLanguage.AR to "تعذر رفع الشعار. حاول مرة أخرى.", AppLanguage.EN to "Could not upload logo. Try again."),
        "settings_saved_success" to mapOf(AppLanguage.AR to "تم حفظ تغييرات المتجر بنجاح", AppLanguage.EN to "Store settings saved successfully"),
        "btn_save_store_changes" to mapOf(AppLanguage.AR to "حفظ تغييرات المتجر", AppLanguage.EN to "Save store changes"),
        "logo_format_error" to mapOf(AppLanguage.AR to "ارفع صورة بصيغة PNG أو JPG أو WebP.", AppLanguage.EN to "Please upload an image in PNG, JPG, or WebP format."),
        "logo_empty_error" to mapOf(AppLanguage.AR to "ملف الشعار فارغ.", AppLanguage.EN to "Logo file is empty."),
        "tab_store_account" to mapOf(AppLanguage.AR to "حساب المتجر", AppLanguage.EN to "Store Account"),
        "tab_personal_account" to mapOf(AppLanguage.AR to "الحساب الشخصي", AppLanguage.EN to "Personal Account"),
        "product_image_format_error" to mapOf(AppLanguage.AR to "ارفع صورة بصيغة PNG أو JPG أو WebP.", AppLanguage.EN to "Please upload a product image in PNG, JPG, or WebP format."),
        "image_empty_error" to mapOf(AppLanguage.AR to "ملف الصورة فارغ.", AppLanguage.EN to "The image file is empty."),
        "image_size_error" to mapOf(AppLanguage.AR to "حجم صورة المنتج يجب ألا يتجاوز 1MB.", AppLanguage.EN to "Product image size must not exceed 1MB."),
        "change_password" to mapOf(AppLanguage.AR to "تغيير كلمة المرور", AppLanguage.EN to "Change Password"),
        "logout" to mapOf(AppLanguage.AR to "تسجيل الخروج", AppLanguage.EN to "Logout"),
        "of" to mapOf(AppLanguage.AR to "من", AppLanguage.EN to "of"),
        "generated_suggestions" to mapOf(AppLanguage.AR to "الاقتراحات المولدة", AppLanguage.EN to "Generated Suggestions"),
        "variant_format" to mapOf(AppLanguage.AR to "صيغة: %s", AppLanguage.EN to "Format: %s"),
        "reply_copied" to mapOf(AppLanguage.AR to "تم نسخ الرد بنجاح", AppLanguage.EN to "Reply copied successfully"),
        "copy" to mapOf(AppLanguage.AR to "نسخ", AppLanguage.EN to "Copy"),
        "caption_copied" to mapOf(AppLanguage.AR to "تم نسخ الكابشن بنجاح", AppLanguage.EN to "Caption copied successfully"),
        "unexpected_error" to mapOf(AppLanguage.AR to "حدث خطأ غير متوقع", AppLanguage.EN to "An unexpected error occurred"),
        "delete_account" to mapOf(AppLanguage.AR to "حذف الحساب", AppLanguage.EN to "Delete Account"),
        "delete_account_desc" to mapOf(AppLanguage.AR to "سيتم حذف حسابك وبياناتك المحلية، وقد تحتاج إلى إعادة التسجيل للوصول مرة أخرى.", AppLanguage.EN to "Your account and local data will be deleted, and you may need to register again to access it."),
        "btn_cancel" to mapOf(AppLanguage.AR to "إلغاء", AppLanguage.EN to "Cancel"),
        "account_delete_failed" to mapOf(AppLanguage.AR to "تعذر حذف الحساب الآن.", AppLanguage.EN to "Could not delete the account right now."),
        "app_settings" to mapOf(AppLanguage.AR to "إعدادات التطبيق", AppLanguage.EN to "App Settings"),
        "store_logo" to mapOf(AppLanguage.AR to "شعار المتجر", AppLanguage.EN to "Store Logo"),
        "personal_account_desc" to mapOf(AppLanguage.AR to "مرحباً بك، إدارة حسابك ومعلوماتك الشخصية في مكان آمن.", AppLanguage.EN to "Welcome, manage your account and personal info in a secure place."),
        "personal_account" to mapOf(AppLanguage.AR to "حساب شخصي", AppLanguage.EN to "Personal Account"),
        "account_info" to mapOf(AppLanguage.AR to "معلومات الحساب", AppLanguage.EN to "Account Information"),
        "update_password_desc" to mapOf(AppLanguage.AR to "قم بتحديث كلمة المرور الخاصة بحسابك", AppLanguage.EN to "Update your account password"),
        "logout_desc" to mapOf(AppLanguage.AR to "تسجيل الخروج من التطبيق الحالي", AppLanguage.EN to "Sign out of the current application"),
        "verified_store" to mapOf(AppLanguage.AR to "متجر موثق", AppLanguage.EN to "Verified Store"),
        "store_slogan" to mapOf(AppLanguage.AR to "أدوات ذكية لتجارتك اليومية", AppLanguage.EN to "Smart tools for your daily business"),
        "business_category" to mapOf(AppLanguage.AR to "تصنيف النشاط التجاري", AppLanguage.EN to "Business Category"),
        "contact_phone" to mapOf(AppLanguage.AR to "رقم التواصل", AppLanguage.EN to "Contact Phone"),
        "invoice_notifications_prefs" to mapOf(AppLanguage.AR to "تفضيلات الفواتير والإشعارات", AppLanguage.EN to "Invoice & Notification Preferences"),
        "billing_prefs_value" to mapOf(AppLanguage.AR to "بريد إلكتروني، إشعارات داخل التطبيق", AppLanguage.EN to "Email, in-app notifications"),
        "save_store_changes" to mapOf(AppLanguage.AR to "حفظ تغييرات المتجر", AppLanguage.EN to "Save Store Changes"),
        "category_default_value" to mapOf(AppLanguage.AR to "توفير", AppLanguage.EN to "Tawfeer (Retail)"),
        "customers_desc" to mapOf(AppLanguage.AR to "إدارة علاقاتك وتواصل مع عملائك بسهولة.", AppLanguage.EN to "Manage your relations and communicate with clients easily."),
        "total_customers" to mapOf(AppLanguage.AR to "إجمالي العملاء", AppLanguage.EN to "Total Customers"),
        "active_customers" to mapOf(AppLanguage.AR to "عملاء نشطين", AppLanguage.EN to "Active Customers"),
        "new_customers" to mapOf(AppLanguage.AR to "عملاء جدد", AppLanguage.EN to "New Customers"),
        "most_active_customers" to mapOf(AppLanguage.AR to "أكثر تعاملاً", AppLanguage.EN to "Top Customers"),
        "dark_mode_label" to mapOf(AppLanguage.AR to "الوضع الداكن", AppLanguage.EN to "Dark Mode"),
        "light_mode_label" to mapOf(AppLanguage.AR to "الوضع الفاتح", AppLanguage.EN to "Light Mode"),
        "current_plan" to mapOf(AppLanguage.AR to "الخطة الحالية", AppLanguage.EN to "Current Plan"),
        "free_plan" to mapOf(AppLanguage.AR to "الخطة المجانية", AppLanguage.EN to "Free Plan"),
        "starter_plan" to mapOf(AppLanguage.AR to "خطة البداية", AppLanguage.EN to "Starter Plan"),
        "ai_uses" to mapOf(AppLanguage.AR to "استخدامات AI", AppLanguage.EN to "AI Uses"),
        "retry" to mapOf(AppLanguage.AR to "إعادة المحاولة", AppLanguage.EN to "Retry"),
        "store_settings" to mapOf(AppLanguage.AR to "إعدادات المتجر", AppLanguage.EN to "Store Settings"),
        "store_settings_desc" to mapOf(AppLanguage.AR to "الشعار، بيانات النشاط، العملة والدولة", AppLanguage.EN to "Logo, business info, currency and country"),
        "account_settings" to mapOf(AppLanguage.AR to "إعدادات الحساب", AppLanguage.EN to "Account Settings"),
        "account_settings_desc" to mapOf(AppLanguage.AR to "البريد، كلمة المرور، بيانات الحساب", AppLanguage.EN to "Email, password, account info"),
        "app_settings_desc" to mapOf(AppLanguage.AR to "اللغة، المظهر، تفضيلات التطبيق", AppLanguage.EN to "Language, theme, app preferences"),
        "upgrade_plan" to mapOf(AppLanguage.AR to "ترقية الخطة", AppLanguage.EN to "Upgrade Plan"),
        "upgrade_plan_desc" to mapOf(AppLanguage.AR to "افتح حدود أعلى وميزات احترافية", AppLanguage.EN to "Unlock higher limits and pro features"),
        "rise_to_pro" to mapOf(AppLanguage.AR to "ارتق بتجاريو برو", AppLanguage.EN to "Upgrade to Tijario Pro"),
        "pro_benefits_desc" to mapOf(AppLanguage.AR to "حدود أعلى للمستندات والذكاء الاصطناعي وتجربة أعمال أكثر احترافية.", AppLanguage.EN to "Higher limits for documents, AI, and a more professional business experience."),
        "coming_soon_upgrade" to mapOf(AppLanguage.AR to "قريبًا: تفعيل الترقية", AppLanguage.EN to "Coming Soon: Activate Upgrade"),
        "documents" to mapOf(AppLanguage.AR to "المستندات", AppLanguage.EN to "Documents"),
        "remaining" to mapOf(AppLanguage.AR to "المتبقي: %s", AppLanguage.EN to "%s remaining"),
        "add_new_item" to mapOf(AppLanguage.AR to "إضافة بند جديد", AppLanguage.EN to "Add New Item"),
        "suitable_growing_stores" to mapOf(AppLanguage.AR to "مناسب للمتاجر النامية", AppLanguage.EN to "Suitable for growing stores"),
        "business_lots_docs" to mapOf(AppLanguage.AR to "للأعمال كثيرة المستندات", AppLanguage.EN to "For document-heavy businesses"),
        "more_monthly_docs" to mapOf(AppLanguage.AR to "مستندات شهرية أكثر", AppLanguage.EN to "More monthly documents"),
        "higher_ai_uses" to mapOf(AppLanguage.AR to "استخدامات AI أعلى", AppLanguage.EN to "Higher AI limits"),
        "pro_pdf_templates" to mapOf(AppLanguage.AR to "قوالب PDF احترافية", AppLanguage.EN to "Professional PDF templates"),
        "advanced_features_support" to mapOf(AppLanguage.AR to "دعم ميزات متقدمة", AppLanguage.EN to "Advanced features support"),
        "higher_limits" to mapOf(AppLanguage.AR to "حدود أعلى", AppLanguage.EN to "Higher limits"),
        "priority_features" to mapOf(AppLanguage.AR to "أولوية في الميزات", AppLanguage.EN to "Priority features"),
        "more_flexible_management" to mapOf(AppLanguage.AR to "إدارة أكثر مرونة", AppLanguage.EN to "More flexible management"),
        "ready_to_expand" to mapOf(AppLanguage.AR to "جاهز للتوسع", AppLanguage.EN to "Ready to scale"),
        "no_email_associated" to mapOf(AppLanguage.AR to "لا يوجد بريد إلكتروني مرتبط بالحساب", AppLanguage.EN to "No email associated with this account"),
        "all_amounts_in" to mapOf(AppLanguage.AR to "جميع الأرقام بـ %s", AppLanguage.EN to "All amounts in %s"),
        "total_sales" to mapOf(AppLanguage.AR to "إجمالي المبيعات", AppLanguage.EN to "Total Sales"),
        "latest_documents" to mapOf(AppLanguage.AR to "آخر المستندات", AppLanguage.EN to "Latest Documents"),
        "view_all" to mapOf(AppLanguage.AR to "عرض الكل", AppLanguage.EN to "View All"),
        "available_stock_optional" to mapOf(AppLanguage.AR to "الكمية المتوفرة (اختياري)", AppLanguage.EN to "Available Quantity (Optional)"),
        "invoice_num" to mapOf(AppLanguage.AR to "فاتورة %s", AppLanguage.EN to "Invoice %s"),
        "quote_num" to mapOf(AppLanguage.AR to "عرض سعر %s", AppLanguage.EN to "Quote %s"),
        "customer_label" to mapOf(AppLanguage.AR to "العميل: %s", AppLanguage.EN to "Customer: %s"),
        "total_label" to mapOf(AppLanguage.AR to "الإجمالي: %s %s", AppLanguage.EN to "Total: %s %s"),
        "payment_status_label" to mapOf(AppLanguage.AR to "حالة الدفع: %s", AppLanguage.EN to "Payment Status: %s"),
        "document_preview" to mapOf(AppLanguage.AR to "معاينة أولية", AppLanguage.EN to "Preview"),
        "invoice_language" to mapOf(AppLanguage.AR to "لغة الفاتورة", AppLanguage.EN to "Invoice Language"),
        "templates" to mapOf(AppLanguage.AR to "القوالب", AppLanguage.EN to "Templates"),
        "from" to mapOf(AppLanguage.AR to "من", AppLanguage.EN to "From"),
        "bill_to" to mapOf(AppLanguage.AR to "إلى (العميل)", AppLanguage.EN to "Bill To"),
        "add_client" to mapOf(AppLanguage.AR to "اختر عميل", AppLanguage.EN to "Add Client"),
        "items_count" to mapOf(AppLanguage.AR to "البنود (%d)", AppLanguage.EN to "Items (%d)"),
        "subtotal" to mapOf(AppLanguage.AR to "الإجمالي الفرعي", AppLanguage.EN to "Subtotal"),
        "edit_item_title" to mapOf(AppLanguage.AR to "تعديل بند", AppLanguage.EN to "Edit Item"),
        "item_name_label" to mapOf(AppLanguage.AR to "اسم البند", AppLanguage.EN to "Item Name"),
        "item_price_label" to mapOf(AppLanguage.AR to "سعر المنتج", AppLanguage.EN to "Item Price"),
        "item_qty_label" to mapOf(AppLanguage.AR to "الكمية", AppLanguage.EN to "Item Quantity"),
        "unit_measure_label" to mapOf(AppLanguage.AR to "وحدة القياس", AppLanguage.EN to "Unit of Measure"),
        "unit_none" to mapOf(AppLanguage.AR to "لا شيء", AppLanguage.EN to "None"),
        "item_discount" to mapOf(AppLanguage.AR to "الخصم", AppLanguage.EN to "Discount"),
        "item_tax_rate" to mapOf(AppLanguage.AR to "نسبة الضريبة", AppLanguage.EN to "Tax Rate"),
        "amount_label" to mapOf(AppLanguage.AR to "الإجمالي", AppLanguage.EN to "Amount"),
        "item_desc_label" to mapOf(AppLanguage.AR to "الوصف", AppLanguage.EN to "Item Description"),
        "btn_preview" to mapOf(AppLanguage.AR to "معاينة", AppLanguage.EN to "Preview"),
        "btn_save" to mapOf(AppLanguage.AR to "حفظ", AppLanguage.EN to "Save"),
        "created_on" to mapOf(AppLanguage.AR to "أنشئت في %s", AppLanguage.EN to "Created on %s"),
        "add_item" to mapOf(AppLanguage.AR to "إضافة بند", AppLanguage.EN to "Add Item"),
        "invoice_info_title" to mapOf(AppLanguage.AR to "بيانات الفاتورة", AppLanguage.EN to "Invoice Info"),
        "invoice_number" to mapOf(AppLanguage.AR to "رقم الفاتورة", AppLanguage.EN to "Invoice Number"),
        "creation_date" to mapOf(AppLanguage.AR to "تاريخ الإنشاء", AppLanguage.EN to "Creation Date"),
        "due_terms" to mapOf(AppLanguage.AR to "شروط الدفع", AppLanguage.EN to "Due Terms"),
        "due_date" to mapOf(AppLanguage.AR to "تاريخ الاستحقاق", AppLanguage.EN to "Due Date"),
        "po_number" to mapOf(AppLanguage.AR to "رقم أمر الشراء P.O.#", AppLanguage.EN to "P.O.#"),
        "invoice_title_name" to mapOf(AppLanguage.AR to "اسم عنوان الفاتورة", AppLanguage.EN to "Invoice Title Name"),
        "select_template" to mapOf(AppLanguage.AR to "اختر القالب", AppLanguage.EN to "Select a Template"),
        "export_view_pdf" to mapOf(AppLanguage.AR to "عرض PDF", AppLanguage.EN to "View PDF"),
        "export_saved_downloads" to mapOf(AppLanguage.AR to "تم حفظ الملف في التنزيلات", AppLanguage.EN to "File saved in Downloads"),
        "export_send_email" to mapOf(AppLanguage.AR to "إرسال بالبريد", AppLanguage.EN to "Send via Email"),
        "export_share_pdf" to mapOf(AppLanguage.AR to "مشاركة PDF", AppLanguage.EN to "Share PDF"),
        "export_share_text" to mapOf(AppLanguage.AR to "مشاركة النص", AppLanguage.EN to "Share Text"),
        "export_no_app_found" to mapOf(AppLanguage.AR to "لا يوجد تطبيق مناسب لتنفيذ هذا الإجراء", AppLanguage.EN to "No suitable app found to execute this action"),
        "export_error_generic" to mapOf(AppLanguage.AR to "تعذر تنفيذ الإجراء الآن", AppLanguage.EN to "Action cannot be executed now"),
        "doc_detail_invoice" to mapOf(AppLanguage.AR to "تفاصيل الفاتورة", AppLanguage.EN to "Invoice Details"),
        "doc_detail_quote" to mapOf(AppLanguage.AR to "تفاصيل عرض السعر", AppLanguage.EN to "Quote Details"),
        "preparing_doc" to mapOf(AppLanguage.AR to "جاري تجهيز المستند...", AppLanguage.EN to "Preparing document..."),
        "open_export_options" to mapOf(AppLanguage.AR to "فتح خيارات التصدير", AppLanguage.EN to "Open Export Options"),
        "error_load_doc_detail" to mapOf(AppLanguage.AR to "تعذر تحميل تفاصيل المستند.", AppLanguage.EN to "Could not load document details."),
        "btn_close" to mapOf(AppLanguage.AR to "إغلاق", AppLanguage.EN to "Close"),
        "tax" to mapOf(AppLanguage.AR to "الضريبة", AppLanguage.EN to "Tax"),
        "invoice_terms_cond" to mapOf(AppLanguage.AR to "شروط وأحكام الفاتورة", AppLanguage.EN to "Invoice Terms & Conditions"),
        "selected" to mapOf(AppLanguage.AR to "محددة", AppLanguage.EN to "Selected"),
        "none" to mapOf(AppLanguage.AR to "لا يوجد", AppLanguage.EN to "None"),
        "invoice_signature" to mapOf(AppLanguage.AR to "توقيع المستند", AppLanguage.EN to "Invoice Signature"),
        "signed" to mapOf(AppLanguage.AR to "موقع", AppLanguage.EN to "Signed"),
        "change_template" to mapOf(AppLanguage.AR to "تغيير القالب", AppLanguage.EN to "Change Template"),
        "swipe_change_template" to mapOf(AppLanguage.AR to "مرر لليمين أو اليسار للتغيير بين القوالب مباشرة مع البيانات الحالية.", AppLanguage.EN to "Swipe left or right to switch templates directly with the current data."),
        "select_currency" to mapOf(AppLanguage.AR to "اختر العملة", AppLanguage.EN to "Select Currency"),
        "local_stored_taxes" to mapOf(AppLanguage.AR to "الضرائب المخزنة محلياً", AppLanguage.EN to "Local Stored Taxes"),
        "tax_name" to mapOf(AppLanguage.AR to "اسم الضريبة", AppLanguage.EN to "Tax Name"),
        "rate_percent" to mapOf(AppLanguage.AR to "النسبة %", AppLanguage.EN to "Rate %"),
        "save_new" to mapOf(AppLanguage.AR to "حفظ كجديد", AppLanguage.EN to "Save New"),
        "no_taxes_stored" to mapOf(AppLanguage.AR to "لا توجد ضرائب مخزنة", AppLanguage.EN to "No taxes stored"),
        "stored_payment_methods" to mapOf(AppLanguage.AR to "طرق الدفع المخزنة", AppLanguage.EN to "Stored Payment Methods"),
        "new_method_name" to mapOf(AppLanguage.AR to "اسم طريقة الدفع الجديدة", AppLanguage.EN to "New Method Name"),
        "payment_cash" to mapOf(AppLanguage.AR to "نقدي", AppLanguage.EN to "Cash"),
        "payment_mada" to mapOf(AppLanguage.AR to "مدى", AppLanguage.EN to "Mada"),
        "payment_bank_transfer" to mapOf(AppLanguage.AR to "تحويل بنكي", AppLanguage.EN to "Bank Transfer"),
        "stored_terms_cond" to mapOf(AppLanguage.AR to "الشروط والأحكام المخزنة", AppLanguage.EN to "Stored Terms & Conditions"),
        "terms_title" to mapOf(AppLanguage.AR to "العنوان", AppLanguage.EN to "Title"),
        "terms_content" to mapOf(AppLanguage.AR to "نص الشروط", AppLanguage.EN to "Terms Content"),
        "save_new_terms" to mapOf(AppLanguage.AR to "حفظ الشروط الجديدة", AppLanguage.EN to "Save New Terms"),
        "no_terms_stored" to mapOf(AppLanguage.AR to "لا توجد نماذج شروط مخزنة", AppLanguage.EN to "No terms templates stored"),
        "signatures" to mapOf(AppLanguage.AR to "التوقيعات", AppLanguage.EN to "Signatures"),
        "signature_owner_name" to mapOf(AppLanguage.AR to "اسم صاحب التوقيع", AppLanguage.EN to "Signature Owner Name"),
        "draw_signature_here" to mapOf(AppLanguage.AR to "ارسم توقيعك هنا", AppLanguage.EN to "Draw your signature here"),
        "save_signature" to mapOf(AppLanguage.AR to "حفظ التوقيع", AppLanguage.EN to "Save Signature"),
        "draw_new_signature" to mapOf(AppLanguage.AR to "رسم توقيع جديد", AppLanguage.EN to "Draw New Signature"),
        "no_signatures_stored" to mapOf(AppLanguage.AR to "لا توجد توقيعات مخزنة", AppLanguage.EN to "No signatures stored"),
        "edit" to mapOf(AppLanguage.AR to "تعديل", AppLanguage.EN to "Edit"),
        "no_tax" to mapOf(AppLanguage.AR to "بدون ضريبة", AppLanguage.EN to "No Tax"),
        "final_total" to mapOf(AppLanguage.AR to "الإجمالي النهائي", AppLanguage.EN to "Final Total"),
        "payment_status" to mapOf(AppLanguage.AR to "حالة الدفع", AppLanguage.EN to "Payment Status"),
        "amount_paid" to mapOf(AppLanguage.AR to "المبلغ المدفوع", AppLanguage.EN to "Amount Paid"),
        "additional_invoice_options" to mapOf(AppLanguage.AR to "خيارات الفاتورة الإضافية", AppLanguage.EN to "Additional Options"),
        "payment_method" to mapOf(AppLanguage.AR to "طريقة الدفع", AppLanguage.EN to "Payment Method"),
        "not_specified" to mapOf(AppLanguage.AR to "لم تحدد", AppLanguage.EN to "None"),
        "not_signed" to mapOf(AppLanguage.AR to "لم يوقع", AppLanguage.EN to "None"),
        "terms_cond" to mapOf(AppLanguage.AR to "الشروط والأحكام", AppLanguage.EN to "Terms & Conditions"),
        "specified" to mapOf(AppLanguage.AR to "محدد", AppLanguage.EN to "Signed"),
        "template_label" to mapOf(AppLanguage.AR to "القالب: %s", AppLanguage.EN to "Template: %s"),
        "app_logo_desc" to mapOf(AppLanguage.AR to "شعار التطبيق", AppLanguage.EN to "App Logo"),
        "field_fullname" to mapOf(AppLanguage.AR to "الاسم", AppLanguage.EN to "Name"),
        "field_store_name" to mapOf(AppLanguage.AR to "اسم المتجر", AppLanguage.EN to "Store Name"),
        "field_customer_name" to mapOf(AppLanguage.AR to "اسم العميل", AppLanguage.EN to "Customer Name"),
        "field_item_name" to mapOf(AppLanguage.AR to "اسم البند", AppLanguage.EN to "Item Name"),
        "field_final_tax" to mapOf(AppLanguage.AR to "الضريبة النهائية", AppLanguage.EN to "Final Tax"),
        "field_price" to mapOf(AppLanguage.AR to "السعر", AppLanguage.EN to "Price"),
        "validation_required" to mapOf(AppLanguage.AR to "%s مطلوب", AppLanguage.EN to "%s is required"),
        "validation_email_required" to mapOf(AppLanguage.AR to "البريد الإلكتروني مطلوب", AppLanguage.EN to "Email is required"),
        "validation_email_invalid" to mapOf(AppLanguage.AR to "أدخل بريدًا إلكترونيًا صحيحًا", AppLanguage.EN to "Enter a valid email address"),
        "validation_password_required" to mapOf(AppLanguage.AR to "كلمة المرور مطلوبة", AppLanguage.EN to "Password is required"),
        "validation_password_min_length" to mapOf(AppLanguage.AR to "كلمة المرور يجب ألا تقل عن 6 أحرف", AppLanguage.EN to "Password must be at least 6 characters"),
        "validation_whatsapp_required" to mapOf(AppLanguage.AR to "رقم واتساب مطلوب", AppLanguage.EN to "WhatsApp number is required"),
        "validation_whatsapp_invalid" to mapOf(AppLanguage.AR to "أدخل رقم واتساب صحيح", AppLanguage.EN to "Enter a valid WhatsApp number"),
        "validation_positive_int" to mapOf(AppLanguage.AR to "%s يجب أن يكون رقمًا أكبر من صفر", AppLanguage.EN to "%s must be a positive integer"),
        "validation_non_negative_int" to mapOf(AppLanguage.AR to "%s يجب أن يكون رقمًا صحيحًا غير سالب", AppLanguage.EN to "%s must be a non-negative integer"),
        "validation_non_negative_money" to mapOf(AppLanguage.AR to "%s يجب أن يكون رقمًا غير سالب", AppLanguage.EN to "%s must be a non-negative number"),
        "error_connect_server" to mapOf(AppLanguage.AR to "تعذر الاتصال بالخادم. يرجى التحقق من اتصالك بالإنترنت.", AppLanguage.EN to "Failed to connect to server. Please check your internet connection."),
        "error_timeout" to mapOf(AppLanguage.AR to "انتهت مهلة الاتصال بالخادم. يرجى المحاولة مرة أخرى.", AppLanguage.EN to "Connection timeout. Please try again."),
        "error_network" to mapOf(AppLanguage.AR to "حدث خطأ في الاتصال بالشبكة.", AppLanguage.EN to "A network error occurred."),
        "error_invalid_credentials" to mapOf(AppLanguage.AR to "البريد الإلكتروني أو كلمة المرور غير صحيحة.", AppLanguage.EN to "Invalid email or password."),
        "error_email_not_confirmed" to mapOf(AppLanguage.AR to "الرجاء تأكيد البريد الإلكتروني أولاً.", AppLanguage.EN to "Please confirm your email first."),
        "error_email_already_registered" to mapOf(AppLanguage.AR to "البريد الإلكتروني مسجل بالفعل.", AppLanguage.EN to "Email is already registered."),
        "error_rate_limit" to mapOf(AppLanguage.AR to "تم تجاوز حد إرسال الرموز. يرجى المحاولة بعد قليل.", AppLanguage.EN to "Rate limit exceeded. Please try again in a few moments."),
        "error_invalid_flow_state" to mapOf(AppLanguage.AR to "رمز التحقق غير صحيح أو انتهت صلاحيته.", AppLanguage.EN to "Verification code is invalid or expired."),
        "error_limit_exceeded" to mapOf(AppLanguage.AR to "لقد تجاوزت الحد الشهري المسموح به للعمليات.", AppLanguage.EN to "You have exceeded the monthly limit for operations."),
        "error_generic" to mapOf(AppLanguage.AR to "حدث خطأ غير متوقع. يرجى المحاولة لاحقاً.", AppLanguage.EN to "An unexpected error occurred. Please try again later."),
        "error_session_expired" to mapOf(AppLanguage.AR to "انتهت صلاحية الجلسة. يرجى تسجيل الدخول مرة أخرى.", AppLanguage.EN to "Session expired. Please log in again."),
        "error_duplicate_customer" to mapOf(AppLanguage.AR to "هذا العميل مضاف بالفعل.", AppLanguage.EN to "This customer is already added."),
        "error_duplicate_product" to mapOf(AppLanguage.AR to "هذا المنتج مضاف بالفعل.", AppLanguage.EN to "This product is already added."),
        "error_server" to mapOf(AppLanguage.AR to "حدث خطأ في الخادم الداخلي.", AppLanguage.EN to "An internal server error occurred."),
        "error_system_with_code" to mapOf(AppLanguage.AR to "حدث خطأ في النظام (%s).", AppLanguage.EN to "A system error occurred (%s)."),
        "error_session_check_failed" to mapOf(AppLanguage.AR to "فشل فحص حالة الجلسة", AppLanguage.EN to "Failed to check session state"),
        "error_after_verification_check" to mapOf(AppLanguage.AR to "حدث خطأ أثناء فحص البيانات بعد التحقق.", AppLanguage.EN to "An error occurred while verifying data."),
        "saudi_arabia" to mapOf(AppLanguage.AR to "السعودية", AppLanguage.EN to "Saudi Arabia"),
    )

    fun getString(key: String, lang: AppLanguage): String {
        return translations[key]?.get(lang) ?: key
    }
}

@Composable
fun t(key: String): String {
    val lang = LocalLanguage.current
    return Localization.getString(key, lang)
}
