package app.tijario.config

import androidx.compose.runtime.Composable
import androidx.compose.runtime.compositionLocalOf

enum class AppLanguage { AR, EN }

val LocalLanguage = compositionLocalOf { AppLanguage.AR }

object Localization {
    private val translations = mapOf(
        "app_name" to mapOf(AppLanguage.AR to "ØªØ¬Ø§Ø±ÙŠÙˆ", AppLanguage.EN to "Tijario"),
        "app_slogan" to mapOf(AppLanguage.AR to "Ø£Ø¯Ø± ØªØ¬Ø§Ø±ØªÙƒ ÙˆÙÙˆØ§ØªÙŠØ±Ùƒ Ø¨Ø°ÙƒØ§Ø¡ ÙˆØ³Ø±Ø¹Ø©", AppLanguage.EN to "Manage your business and invoices smartly"),

        // Navigation / Tabs
        "tab_home" to mapOf(AppLanguage.AR to "Ø§Ù„Ø±Ø¦ÙŠØ³ÙŠØ©", AppLanguage.EN to "Home"),
        "tab_customers" to mapOf(AppLanguage.AR to "Ø§Ù„Ø¹Ù…Ù„Ø§Ø¡", AppLanguage.EN to "Customers"),
        "tab_products" to mapOf(AppLanguage.AR to "Ø§Ù„Ù…Ù†ØªØ¬Ø§Øª", AppLanguage.EN to "Products"),
        "tab_documents" to mapOf(AppLanguage.AR to "Ø§Ù„Ù…Ø³ØªÙ†Ø¯Ø§Øª", AppLanguage.EN to "Documents"),
        "tab_ai" to mapOf(AppLanguage.AR to "ØªØ¬Ø§Ø±ÙŠÙˆ AI", AppLanguage.EN to "Tijario AI"),
        "tab_account" to mapOf(AppLanguage.AR to "Ø§Ù„Ø­Ø³Ø§Ø¨", AppLanguage.EN to "Account"),

        // Login Screen
        "login_title" to mapOf(AppLanguage.AR to "ØªØ³Ø¬ÙŠÙ„ Ø§Ù„Ø¯Ø®ÙˆÙ„", AppLanguage.EN to "Login"),
        "login_subtitle" to mapOf(AppLanguage.AR to "Ø§Ø¯Ø®Ù„ Ø¥Ù„Ù‰ Ø­Ø³Ø§Ø¨ ØªØ¬Ø§Ø±ÙŠ Ù„Ù…ØªØ§Ø¨Ø¹Ø© Ø¥Ø¯Ø§Ø±Ø© Ù…ØªØ¬Ø±Ùƒ.", AppLanguage.EN to "Sign in to manage your store and invoices."),
        "email" to mapOf(AppLanguage.AR to "Ø§Ù„Ø¨Ø±ÙŠØ¯ Ø§Ù„Ø¥Ù„ÙƒØªØ±ÙˆÙ†ÙŠ", AppLanguage.EN to "Email"),
        "password" to mapOf(AppLanguage.AR to "ÙƒÙ„Ù…Ø© Ø§Ù„Ù…Ø±ÙˆØ±", AppLanguage.EN to "Password"),
        "forgot_password" to mapOf(AppLanguage.AR to "Ù†Ø³ÙŠØª ÙƒÙ„Ù…Ø© Ø§Ù„Ù…Ø±ÙˆØ±ØŸ", AppLanguage.EN to "Forgot Password?"),
        "btn_login" to mapOf(AppLanguage.AR to "Ø¯Ø®ÙˆÙ„", AppLanguage.EN to "Login"),
        "or" to mapOf(AppLanguage.AR to "Ø£Ùˆ", AppLanguage.EN to "Or"),
        "google_login" to mapOf(AppLanguage.AR to "ØªØ³Ø¬ÙŠÙ„ Ø§Ù„Ø¯Ø®ÙˆÙ„ Ø¨Ø§Ø³ØªØ®Ø¯Ø§Ù… Google", AppLanguage.EN to "Sign in with Google"),
        "google_register" to mapOf(AppLanguage.AR to "Ø§Ù„ØªØ³Ø¬ÙŠÙ„ Ø¨Ø§Ø³ØªØ®Ø¯Ø§Ù… Google", AppLanguage.EN to "Sign up with Google"),
        "no_account" to mapOf(AppLanguage.AR to "Ù„ÙŠØ³ Ù„Ø¯ÙŠÙƒ Ø­Ø³Ø§Ø¨ØŸ ", AppLanguage.EN to "Don't have an account? "),
        "create_account" to mapOf(AppLanguage.AR to "Ø£Ù†Ø´Ø¦ Ø­Ø³Ø§Ø¨Ø§Ù‹ Ø¬Ø¯ÙŠØ¯Ø§Ù‹", AppLanguage.EN to "Create an account"),

        // Register Screen
        "register_title" to mapOf(AppLanguage.AR to "Ø¥Ù†Ø´Ø§Ø¡ Ø­Ø³Ø§Ø¨ Ø¬Ø¯ÙŠØ¯", AppLanguage.EN to "Register"),
        "register_subtitle" to mapOf(AppLanguage.AR to "Ø§Ù†Ø¶Ù… Ø¥Ù„Ù‰ ØªØ¬Ø§Ø±ÙŠÙˆ ÙˆØ§Ø¨Ø¯Ø£ ÙÙŠ ØªÙ†Ø¸ÙŠÙ… Ø£Ø¹Ù…Ø§Ù„Ùƒ Ø§Ù„ÙŠÙˆÙ…", AppLanguage.EN to "Join Tijario and organize your business today"),
        "fullname" to mapOf(AppLanguage.AR to "Ø§Ù„Ø§Ø³Ù… Ø§Ù„ÙƒØ§Ù…Ù„", AppLanguage.EN to "Full Name"),
        "confirm_password" to mapOf(AppLanguage.AR to "ØªØ£ÙƒÙŠØ¯ ÙƒÙ„Ù…Ø© Ø§Ù„Ù…Ø±ÙˆØ±", AppLanguage.EN to "Confirm Password"),
        "validation_confirm_password_required" to mapOf(AppLanguage.AR to "ØªØ£ÙƒÙŠØ¯ ÙƒÙ„Ù…Ø© Ø§Ù„Ù…Ø±ÙˆØ± Ù…Ø·Ù„ÙˆØ¨", AppLanguage.EN to "Confirm password is required"),
        "validation_password_mismatch" to mapOf(AppLanguage.AR to "ÙƒÙ„Ù…ØªØ§ Ø§Ù„Ù…Ø±ÙˆØ± ØºÙŠØ± Ù…ØªØ·Ø§Ø¨Ù‚ØªÙŠÙ†", AppLanguage.EN to "Passwords do not match"),
        "already_have_account" to mapOf(AppLanguage.AR to "Ù„Ø¯ÙŠÙƒ Ø­Ø³Ø§Ø¨ Ø¨Ø§Ù„ÙØ¹Ù„ØŸ ", AppLanguage.EN to "Already have an account? "),

        // Forgot Password
        "reset_password_title" to mapOf(AppLanguage.AR to "Ø§Ø³ØªØ¹Ø§Ø¯Ø© ÙƒÙ„Ù…Ø© Ø§Ù„Ù…Ø±ÙˆØ±", AppLanguage.EN to "Reset Password"),
        "reset_password_subtitle" to mapOf(AppLanguage.AR to "Ø³Ù†Ø±Ø³Ù„ Ù„Ùƒ Ø±Ø§Ø¨Ø·Ø§Ù‹ Ù„Ø¥Ø¹Ø§Ø¯Ø© ØªØ¹ÙŠÙŠÙ† ÙƒÙ„Ù…Ø© Ø§Ù„Ù…Ø±ÙˆØ±", AppLanguage.EN to "We will send you a reset link to your email"),
        "btn_send_reset" to mapOf(AppLanguage.AR to "Ø¥Ø±Ø³Ø§Ù„ Ø±Ø§Ø¨Ø· Ø§Ù„Ø§Ø³ØªØ¹Ø§Ø¯Ø©", AppLanguage.EN to "Send Reset Link"),
        "back_to_login" to mapOf(AppLanguage.AR to "Ø§Ù„Ø¹ÙˆØ¯Ø© Ù„ØªØ³Ø¬ÙŠÙ„ Ø§Ù„Ø¯Ø®ÙˆÙ„", AppLanguage.EN to "Back to Login"),
        "reset_success" to mapOf(AppLanguage.AR to "ØªÙ… Ø¥Ø±Ø³Ø§Ù„ Ø±Ø§Ø¨Ø· Ø§Ø³ØªØ¹Ø§Ø¯Ø© ÙƒÙ„Ù…Ø© Ø§Ù„Ù…Ø±ÙˆØ± Ø¨Ù†Ø¬Ø§Ø­ Ø¥Ù„Ù‰ Ø¨Ø±ÙŠØ¯Ùƒ Ø§Ù„Ø¥Ù„ÙƒØªØ±ÙˆÙ†ÙŠ.", AppLanguage.EN to "Reset link has been successfully sent to your email."),

        // Onboarding / Shop Setup
        "onboarding_title" to mapOf(AppLanguage.AR to "ØªÙ‡ÙŠØ¦Ø© Ø­Ø³Ø§Ø¨ Ù…ØªØ¬Ø±Ùƒ", AppLanguage.EN to "Setup Your Store"),
        "onboarding_subtitle" to mapOf(AppLanguage.AR to "Ø£Ø¯Ø®Ù„ Ø¨ÙŠØ§Ù†Ø§Øª Ù†Ø´Ø§Ø·Ùƒ Ø§Ù„ØªØ¬Ø§Ø±ÙŠ Ù„Ø¨Ø¯Ø¡ Ø¥ØµØ¯Ø§Ø± Ø§Ù„ÙÙˆØ§ØªÙŠØ±", AppLanguage.EN to "Enter business details to start issuing documents"),
        "shop_name" to mapOf(AppLanguage.AR to "Ø§Ø³Ù… Ø§Ù„Ù…ØªØ¬Ø± / Ø§Ù„Ù†Ø´Ø§Ø· Ø§Ù„ØªØ¬Ø§Ø±ÙŠ", AppLanguage.EN to "Store / Business Name"),
        "whatsapp_phone" to mapOf(AppLanguage.AR to "Ø±Ù‚Ù… ÙˆØ§ØªØ³Ø§Ø¨ Ù„Ù„ØªÙˆØ§ØµÙ„", AppLanguage.EN to "WhatsApp Phone Number"),
        "country" to mapOf(AppLanguage.AR to "Ø§Ù„Ø¯ÙˆÙ„Ø©", AppLanguage.EN to "Country"),
        "currency" to mapOf(AppLanguage.AR to "Ø§Ù„Ø¹Ù…Ù„Ø©", AppLanguage.EN to "Currency"),
        "btn_save_continue" to mapOf(AppLanguage.AR to "Ø­ÙØ¸ ÙˆØ¥ÙƒÙ…Ø§Ù„ Ø§Ù„Ø¥Ø¹Ø¯Ø§Ø¯", AppLanguage.EN to "Save & Continue"),

        // Dashboard
        "welcome" to mapOf(AppLanguage.AR to "Ø£Ù‡Ù„Ø§Ù‹ Ø¨Ùƒ ÙÙŠ ØªØ¬Ø§Ø±ÙŠÙˆ ðŸ‘‹", AppLanguage.EN to "Welcome to Tijario ðŸ‘‹"),
        "dash_subtitle" to mapOf(AppLanguage.AR to "Ù…ØªØ§Ø¨Ø¹Ø© Ø³Ø±ÙŠØ¹Ø© Ù„Ø£Ø¯Ø§Ø¡ Ø¹Ù…Ù„Ùƒ Ø§Ù„ØªØ¬Ø§Ø±ÙŠ Ø§Ù„ÙŠÙˆÙ…", AppLanguage.EN to "Quick overview of your business performance"),
        "financial_summary" to mapOf(AppLanguage.AR to "Ø§Ù„Ù…Ù„Ø®Øµ Ø§Ù„Ù…Ø§Ù„ÙŠ Ø§Ù„Ø¹Ø§Ù…", AppLanguage.EN to "Financial Summary"),
        "this_month" to mapOf(AppLanguage.AR to "Ù‡Ø°Ø§ Ø§Ù„Ø´Ù‡Ø±", AppLanguage.EN to "This Month"),
        "paid_invoices" to mapOf(AppLanguage.AR to "Ø§Ù„ÙÙˆØ§ØªÙŠØ± Ø§Ù„Ù…Ø¯ÙÙˆØ¹Ø©", AppLanguage.EN to "Paid Invoices"),
        "pending_quotes" to mapOf(AppLanguage.AR to "Ø¹Ø±ÙˆØ¶ Ø§Ù„Ø£Ø³Ø¹Ø§Ø± Ø§Ù„Ù…Ø¹Ù„Ù‚Ø©", AppLanguage.EN to "Pending Quotes"),
        "quick_actions" to mapOf(AppLanguage.AR to "Ø¥Ø¬Ø±Ø§Ø¡Ø§Øª Ø³Ø±ÙŠØ¹Ø©", AppLanguage.EN to "Quick Actions"),
        "btn_new_invoice" to mapOf(AppLanguage.AR to "ÙØ§ØªÙˆØ±Ø© Ø¬Ø¯ÙŠØ¯Ø©", AppLanguage.EN to "New Invoice"),
        "btn_new_quote" to mapOf(AppLanguage.AR to "Ø¹Ø±Ø¶ Ø³Ø¹Ø± Ø¬Ø¯ÙŠØ¯", AppLanguage.EN to "New Quote"),
        "btn_add_customer" to mapOf(AppLanguage.AR to "Ø¥Ø¶Ø§ÙØ© Ø¹Ù…ÙŠÙ„", AppLanguage.EN to "Add Customer"),

        // Customers Screen
        "customers_title" to mapOf(AppLanguage.AR to "Ø§Ù„Ø¹Ù…Ù„Ø§Ø¡", AppLanguage.EN to "Customers"),
        "customers_subtitle" to mapOf(AppLanguage.AR to "Ø³Ø¬Ù„ Ø§Ù„Ø¹Ù…Ù„Ø§Ø¡ ÙˆØ¥Ø¯Ø§Ø±Ø© Ø§Ù„Ø­Ø³Ø§Ø¨Ø§Øª Ø§Ù„Ù…Ø³Ø¬Ù„Ø©", AppLanguage.EN to "Customer registry and registered accounts"),
        "search_placeholder" to mapOf(AppLanguage.AR to "Ø§Ù„Ø¨Ø­Ø« Ø¹Ù† Ø¹Ù…ÙŠÙ„...", AppLanguage.EN to "Search for a customer..."),

        // Documents Screen
        "documents_title" to mapOf(AppLanguage.AR to "Ø§Ù„Ù…Ø³ØªÙ†Ø¯Ø§Øª", AppLanguage.EN to "Documents"),
        "documents_subtitle" to mapOf(AppLanguage.AR to "Ø§Ø³ØªØ¹Ø±Ø§Ø¶ ÙˆØ¥Ø¯Ø§Ø±Ø© Ø¬Ù…ÙŠØ¹ ÙÙˆØ§ØªÙŠØ±Ùƒ ÙˆØ¹Ø±ÙˆØ¶ Ø§Ù„Ø£Ø³Ø¹Ø§Ø±", AppLanguage.EN to "View and manage all your invoices and quotes"),
        "doc_status_paid" to mapOf(AppLanguage.AR to "Ù…Ø¯ÙÙˆØ¹Ø©", AppLanguage.EN to "Paid"),
        "doc_status_draft" to mapOf(AppLanguage.AR to "Ù…Ø³ÙˆØ¯Ø©", AppLanguage.EN to "Draft"),
        "doc_status_expired" to mapOf(AppLanguage.AR to "Ù…Ù†ØªÙ‡ÙŠØ©", AppLanguage.EN to "Expired"),
        "section_invoices" to mapOf(AppLanguage.AR to "Ù‚Ø³Ù… Ø§Ù„ÙÙˆØ§ØªÙŠØ±", AppLanguage.EN to "Invoices Section"),
        "section_quotes" to mapOf(AppLanguage.AR to "Ù‚Ø³Ù… Ø¹Ø±ÙˆØ¶ Ø§Ù„Ø£Ø³Ø¹Ø§Ø±", AppLanguage.EN to "Quotes Section"),
        "btn_create_invoice" to mapOf(AppLanguage.AR to "Ø¥Ù†Ø´Ø§Ø¡ ÙØ§ØªÙˆØ±Ø© Ø¬Ø¯ÙŠØ¯Ø©", AppLanguage.EN to "Create New Invoice"),
        "btn_create_quote" to mapOf(AppLanguage.AR to "Ø¥Ù†Ø´Ø§Ø¡ Ø¹Ø±Ø¶ Ø³Ø¹Ø± Ø¬Ø¯ÙŠØ¯", AppLanguage.EN to "Create New Quote"),

        // AI Tools Screen
        "ai_title" to mapOf(AppLanguage.AR to "Ù…Ø³Ø§Ø¹Ø¯ ØªØ¬Ø§Ø±ÙŠÙˆ Ø§Ù„Ø°ÙƒÙŠ (AI)", AppLanguage.EN to "Tijario AI Assistant"),
        "ai_subtitle" to mapOf(AppLanguage.AR to "ØµÙŠØ§ØºØ© Ø±Ø¯ÙˆØ¯ Ø§Ù„Ø¹Ù…Ù„Ø§Ø¡ ÙˆÙƒØªØ§Ø¨Ø© Ø§Ù„Ø£ÙˆØµØ§Ù Ù„Ù…Ù†ØªØ¬Ø§ØªÙƒ Ø¨Ù„Ù…Ø­ Ø§Ù„Ø¨ØµØ±", AppLanguage.EN to "Draft replies and write product captions in a flash"),
        "ai_card_title" to mapOf(AppLanguage.AR to "ØµÙŠØ§ØºØ© Ø±Ø¯ Ø°ÙƒÙŠ Ù„Ù„Ø¹Ù…Ù„Ø§Ø¡", AppLanguage.EN to "Draft Smart Reply"),
        "ai_input_placeholder" to mapOf(AppLanguage.AR to "Ø§Ù„ØµÙ‚ Ø±Ø³Ø§Ù„Ø© Ø§Ù„Ø¹Ù…ÙŠÙ„ Ù‡Ù†Ø§...", AppLanguage.EN to "Paste client message here..."),
        "btn_generate_reply" to mapOf(AppLanguage.AR to "ØªÙˆÙ„ÙŠØ¯ Ø§Ù„Ø±Ø¯ Ø§Ù„Ø°ÙƒÙŠ", AppLanguage.EN to "Generate Smart Reply"),
        "ai_suggestion" to mapOf(AppLanguage.AR to "Ø§Ù„Ø±Ø¯ Ø§Ù„Ù…Ù‚ØªØ±Ø­:", AppLanguage.EN to "Suggested Reply:"),
        "tab_ai_reply" to mapOf(AppLanguage.AR to "Ø±Ø¯ Ø°ÙƒÙŠ", AppLanguage.EN to "Smart Reply"),
        "tab_ai_caption" to mapOf(AppLanguage.AR to "ÙƒØ§Ø¨Ø´Ù† Ø°ÙƒÙŠ", AppLanguage.EN to "Smart Caption"),
        "ai_caption_card_title" to mapOf(AppLanguage.AR to "ÙƒØªØ§Ø¨Ø© ÙƒØ§Ø¨Ø´Ù† Ø°ÙƒÙŠ Ù„Ù„Ù…Ù†ØªØ¬Ø§Øª", AppLanguage.EN to "Generate Smart Caption"),
        "ai_caption_input_placeholder" to mapOf(AppLanguage.AR to "Ø§ÙƒØªØ¨ ØªÙØ§ØµÙŠÙ„ Ø£Ùˆ Ù…Ù…ÙŠØ²Ø§Øª Ø§Ù„Ù…Ù†ØªØ¬ Ù‡Ù†Ø§...", AppLanguage.EN to "Type product details or features here..."),
        "btn_generate_caption" to mapOf(AppLanguage.AR to "ØªÙˆÙ„ÙŠØ¯ Ø§Ù„ÙƒØ§Ø¨Ø´Ù† Ø§Ù„Ø°ÙƒÙŠ", AppLanguage.EN to "Generate Smart Caption"),
        "ai_caption_suggestion" to mapOf(AppLanguage.AR to "Ø§Ù„ÙƒØ§Ø¨Ø´Ù† Ø§Ù„Ù…Ù‚ØªØ±Ø­:", AppLanguage.EN to "Suggested Caption:"),

        // Account Screen
        "account_title" to mapOf(AppLanguage.AR to "Ø§Ù„Ø­Ø³Ø§Ø¨ ÙˆØ§Ù„Ø§Ø³ØªØ®Ø¯Ø§Ù…", AppLanguage.EN to "Account & Usage"),
        "settings_lang" to mapOf(AppLanguage.AR to "Ù„ØºØ© Ø§Ù„ØªØ·Ø¨ÙŠÙ‚", AppLanguage.EN to "App Language"),
        "settings_theme" to mapOf(AppLanguage.AR to "Ù…Ø¸Ù‡Ø± Ø§Ù„ØªØ·Ø¨ÙŠÙ‚ (Theme)", AppLanguage.EN to "App Theme"),
        "theme_light" to mapOf(AppLanguage.AR to "ÙØ§ØªØ­", AppLanguage.EN to "Light"),
        "theme_dark" to mapOf(AppLanguage.AR to "Ø¯Ø§ÙƒÙ†", AppLanguage.EN to "Dark"),
        "account_pro_badge" to mapOf(AppLanguage.AR to "Ø§Ù„Ø¨Ø§Ù‚Ø© Ø§Ù„Ø§Ø­ØªØ±Ø§ÙÙŠØ© (Pro)", AppLanguage.EN to "Pro Plan"),
        "monthly_limits" to mapOf(AppLanguage.AR to "Ø§Ù„Ø§Ø³ØªÙ‡Ù„Ø§Ùƒ ÙˆØ§Ù„Ø­Ø¯ÙˆØ¯ Ø§Ù„Ø´Ù‡Ø±ÙŠØ©", AppLanguage.EN to "Monthly Limits & Usage"),
        "limit_docs" to mapOf(AppLanguage.AR to "Ø¹Ø±ÙˆØ¶ Ø§Ù„Ø£Ø³Ø¹Ø§Ø± ÙˆØ§Ù„ÙÙˆØ§ØªÙŠØ± Ø§Ù„Ù…ØªØ¨Ù‚ÙŠØ©", AppLanguage.EN to "Remaining Quotes & Invoices"),
        "limit_ai" to mapOf(AppLanguage.AR to "Ø¹Ù…Ù„ÙŠØ§Øª Ø§Ù„Ø°ÙƒØ§Ø¡ Ø§Ù„Ø§ØµØ·Ù†Ø§Ø¹ÙŠ (AI)", AppLanguage.EN to "AI Operations"),
        "store_premium" to mapOf(AppLanguage.AR to "Ù…ØªØ¬Ø± ØªØ¬Ø§Ø±ÙŠÙˆ Ø§Ù„ÙØ§Ø®Ø±", AppLanguage.EN to "Tijario Premium Store"),

        // Form Screens
        "form_client_info" to mapOf(AppLanguage.AR to "Ø¨ÙŠØ§Ù†Ø§Øª Ø§Ù„Ø¹Ù…ÙŠÙ„ Ø§Ù„Ù…Ø³ØªÙ‡Ø¯Ù", AppLanguage.EN to "Target Customer Details"),
        "form_items_info" to mapOf(AppLanguage.AR to "ØªÙØ§ØµÙŠÙ„ Ø§Ù„Ø¨Ù†ÙˆØ¯ ÙˆØ§Ù„Ø£Ø³Ø¹Ø§Ø±", AppLanguage.EN to "Items & Pricing Details"),
        "form_item_name" to mapOf(AppLanguage.AR to "Ø§Ø³Ù… Ø§Ù„Ø¨Ù†Ø¯ / Ø§Ù„Ø®Ø¯Ù…Ø©", AppLanguage.EN to "Item / Service Name"),
        "form_quantity" to mapOf(AppLanguage.AR to "Ø§Ù„ÙƒÙ…ÙŠØ©", AppLanguage.EN to "Quantity"),
        "form_unit_price" to mapOf(AppLanguage.AR to "Ø³Ø¹Ø± Ø§Ù„ÙˆØ­Ø¯Ø©", AppLanguage.EN to "Unit Price"),
        "form_discount" to mapOf(AppLanguage.AR to "Ø§Ù„Ø®ØµÙ…", AppLanguage.EN to "Discount"),
        "form_extra_fees" to mapOf(AppLanguage.AR to "Ø±Ø³ÙˆÙ… Ø¥Ø¶Ø§ÙÙŠØ©", AppLanguage.EN to "Extra Fees"),
        "btn_save_doc" to mapOf(AppLanguage.AR to "ØªÙˆÙ„ÙŠØ¯ ÙˆØ­ÙØ¸ Ø§Ù„Ù…Ø³ØªÙ†Ø¯", AppLanguage.EN to "Generate & Save Document"),
        "btn_save_customer" to mapOf(AppLanguage.AR to "Ø­ÙØ¸ Ø¨ÙŠØ§Ù†Ø§Øª Ø§Ù„Ø¹Ù…ÙŠÙ„", AppLanguage.EN to "Save Customer Data"),
        "btn_save_settings" to mapOf(AppLanguage.AR to "Ø­ÙØ¸ Ø§Ù„ØªØºÙŠÙŠØ±Ø§Øª", AppLanguage.EN to "Save Changes"),
        "city" to mapOf(AppLanguage.AR to "Ø§Ù„Ù…Ø¯ÙŠÙ†Ø©", AppLanguage.EN to "City"),
        "notes" to mapOf(AppLanguage.AR to "Ù…Ù„Ø§Ø­Ø¸Ø§Øª Ø¥Ø¶Ø§ÙÙŠØ©", AppLanguage.EN to "Additional Notes"),
        "terms" to mapOf(AppLanguage.AR to "Ø§Ù„Ø´Ø±ÙˆØ· ÙˆØ§Ù„Ø£Ø­ÙƒØ§Ù… Ø§Ù„Ø§ÙØªØ±Ø§Ø¶ÙŠØ© Ù„Ù„ÙÙˆØ§ØªÙŠØ±", AppLanguage.EN to "Default Invoice Terms"),
        "btn_back" to mapOf(AppLanguage.AR to "Ø±Ø¬ÙˆØ¹", AppLanguage.EN to "Back"),
        "config_req" to mapOf(AppLanguage.AR to "Ø¥Ø¹Ø¯Ø§Ø¯Ø§Øª Ø§Ù„Ø§ØªØµØ§Ù„ Ù…Ø·Ù„ÙˆØ¨Ø©", AppLanguage.EN to "Connection Settings Required"),

        // Products & Services Screen
        "products_title" to mapOf(AppLanguage.AR to "Ø§Ù„Ù…Ù†ØªØ¬Ø§Øª ÙˆØ§Ù„Ø®Ø¯Ù…Ø§Øª", AppLanguage.EN to "Products & Services"),
        "products_subtitle" to mapOf(AppLanguage.AR to "Ø¥Ø¯Ø§Ø±Ø© Ù…Ø®Ø²ÙˆÙ† Ù…Ù†ØªØ¬Ø§ØªÙƒ ÙˆØ§Ù„Ø®Ø¯Ù…Ø§Øª Ø§Ù„ØªÙŠ ØªÙ‚Ø¯Ù…Ù‡Ø§", AppLanguage.EN to "Manage inventory of your products and services"),
        "search_products" to mapOf(AppLanguage.AR to "Ø§Ù„Ø¨Ø­Ø« Ø¹Ù† Ù…Ù†ØªØ¬ Ø£Ùˆ Ø®Ø¯Ù…Ø©...", AppLanguage.EN to "Search for a product or service..."),
        "btn_add_product" to mapOf(AppLanguage.AR to "Ø¥Ø¶Ø§ÙØ© Ù…Ù†ØªØ¬ Ø£Ùˆ Ø®Ø¯Ù…Ø©", AppLanguage.EN to "Add Product/Service"),
        "product_name" to mapOf(AppLanguage.AR to "Ø§Ø³Ù… Ø§Ù„Ù…Ù†ØªØ¬ / Ø§Ù„Ø®Ø¯Ù…Ø©", AppLanguage.EN to "Product/Service Name"),
        "product_description" to mapOf(AppLanguage.AR to "Ø§Ù„ÙˆØµÙ", AppLanguage.EN to "Description"),
        "product_price" to mapOf(AppLanguage.AR to "Ø§Ù„Ø³Ø¹Ø±", AppLanguage.EN to "Price"),
        "product_kind" to mapOf(AppLanguage.AR to "Ø§Ù„Ù†ÙˆØ¹", AppLanguage.EN to "Type"),
        "kind_product" to mapOf(AppLanguage.AR to "Ù…Ù†ØªØ¬", AppLanguage.EN to "Product"),
        "kind_service" to mapOf(AppLanguage.AR to "Ø®Ø¯Ù…Ø©", AppLanguage.EN to "Service"),
        "btn_save_product" to mapOf(AppLanguage.AR to "Ø­ÙØ¸ Ø§Ù„Ù…Ù†ØªØ¬/Ø§Ù„Ø®Ø¯Ù…Ø©", AppLanguage.EN to "Save Product/Service"),
        "config_req_msg" to mapOf(AppLanguage.AR to "Ø§Ù„Ø±Ø¬Ø§Ø¡ Ø¶Ø¨Ø· Ø¥Ø¹Ø¯Ø§Ø¯Ø§Øª Supabase ÙÙŠ gradle.properties ÙˆØªØ´ØºÙŠÙ„ Ø§Ù„Ø®Ø§Ø¯Ù… Ø£Ùˆ Ø§Ù„ØªØ­Ù‚Ù‚ Ù…Ù† Ø§Ù„Ø§ØªØµØ§Ù„.", AppLanguage.EN to "Please configure Supabase settings in gradle.properties and start the server or verify connection."),
        "limit_reached_title" to mapOf(AppLanguage.AR to "ØªÙ… Ø§Ù„ÙˆØµÙˆÙ„ Ù„Ù„Ø­Ø¯ Ø§Ù„Ø£Ù‚ØµÙ‰", AppLanguage.EN to "Limit Reached"),
        "limit_reached_msg" to mapOf(AppLanguage.AR to "Ù„Ù‚Ø¯ Ø§Ø³ØªÙ‡Ù„ÙƒØª ÙƒØ§Ù…Ù„ Ø§Ù„Ø­Ø¯ Ø§Ù„Ù…Ø³Ù…ÙˆØ­ Ø¨Ù‡ Ù…Ù† Ø§Ù„Ù…Ø³ØªÙ†Ø¯Ø§Øª Ø§Ù„Ù…ØªØ§Ø­Ø© Ù„Ø­Ø³Ø§Ø¨ÙƒØŒ ÙŠØ±Ø¬Ù‰ Ø§Ù„ØªØ±Ù‚ÙŠØ© Ù„Ù„Ø­ØµÙˆÙ„ Ø¹Ù„Ù‰ Ø­Ø¯ Ø£ÙƒØ¨Ø±.", AppLanguage.EN to "You have consumed all allowed documents for your account. Please upgrade to get a higher limit."),
        "btn_ok" to mapOf(AppLanguage.AR to "Ø­Ø³Ù†Ø§Ù‹", AppLanguage.EN to "OK"),
        "uncollected_amounts" to mapOf(AppLanguage.AR to "Ø§Ù„Ù…Ø¨Ø§Ù„Øº ØºÙŠØ± Ø§Ù„Ù…Ø­ØµÙ„Ø©", AppLanguage.EN to "Uncollected Amounts"),
        "open_quotes" to mapOf(AppLanguage.AR to "Ø§Ù„Ø¹Ø±ÙˆØ¶ Ø§Ù„Ù…ÙØªÙˆØ­Ø©", AppLanguage.EN to "Open Quotes"),
        "new_invoice" to mapOf(AppLanguage.AR to "ÙØ§ØªÙˆØ±Ø© Ø¬Ø¯ÙŠØ¯Ø©", AppLanguage.EN to "New Invoice"),
        "new_quote" to mapOf(AppLanguage.AR to "Ø¹Ø±Ø¶ Ø³Ø¹Ø± Ø¬Ø¯ÙŠØ¯", AppLanguage.EN to "New Quote"),
        "add_customer" to mapOf(AppLanguage.AR to "Ø¥Ø¶Ø§ÙØ© Ø¹Ù…ÙŠÙ„", AppLanguage.EN to "Add Customer"),
        "new_product_service" to mapOf(AppLanguage.AR to "Ø¥Ø¶Ø§ÙØ© Ù…Ù†ØªØ¬ Ø£Ùˆ Ø®Ø¯Ù…Ø©", AppLanguage.EN to "Add Product/Service"),
        "ai_assistant_sub" to mapOf(AppLanguage.AR to "Ù…Ø³Ø§Ø¹Ø¯Ùƒ Ø§Ù„Ø°ÙƒÙŠ Ù„Ø£Ø¹Ù…Ø§Ù„Ùƒ", AppLanguage.EN to "Your smart business assistant"),
        "no_docs_yet" to mapOf(AppLanguage.AR to "Ù„Ø§ ØªÙˆØ¬Ø¯ ÙÙˆØ§ØªÙŠØ± Ø£Ùˆ Ø¹Ø±ÙˆØ¶ Ø£Ø³Ø¹Ø§Ø± Ø­ØªÙ‰ Ø§Ù„Ø¢Ù†", AppLanguage.EN to "No invoices or quotes yet"),
        "unknown_customer" to mapOf(AppLanguage.AR to "Ø¹Ù…ÙŠÙ„ ØºÙŠØ± Ù…Ø¹Ø±ÙˆÙ", AppLanguage.EN to "Unknown Customer"),
        "confirm_delete" to mapOf(AppLanguage.AR to "ØªØ£ÙƒÙŠØ¯ Ø§Ù„Ø­Ø°Ù", AppLanguage.EN to "Confirm Delete"),
        "delete_customer_confirm" to mapOf(AppLanguage.AR to "Ù‡Ù„ Ø£Ù†Øª Ù…ØªØ£ÙƒØ¯ Ù…Ù† Ø±ØºØ¨ØªÙƒ ÙÙŠ Ø­Ø°Ù Ø§Ù„Ø¹Ù…ÙŠÙ„ØŸ", AppLanguage.EN to "Are you sure you want to delete this customer?"),
        "delete_customer_error" to mapOf(AppLanguage.AR to "ØªØ¹Ø°Ø± Ø­Ø°Ù Ø§Ù„Ø¹Ù…ÙŠÙ„.", AppLanguage.EN to "Could not delete customer."),
        "delete" to mapOf(AppLanguage.AR to "Ø­Ø°Ù", AppLanguage.EN to "Delete"),
        "cancel" to mapOf(AppLanguage.AR to "Ø¥Ù„ØºØ§Ø¡", AppLanguage.EN to "Cancel"),
        "choose_customer_issue" to mapOf(AppLanguage.AR to "Ø§Ø®ØªØ± Ø§Ù„Ø¹Ù…ÙŠÙ„ Ø§Ù„Ù…ÙØ±Ø§Ø¯ Ø¥ØµØ¯Ø§Ø± Ø§Ù„ÙØ§ØªÙˆØ±Ø© Ù„Ù‡", AppLanguage.EN to "Choose the target customer to issue document to"),
        "no_search_results" to mapOf(AppLanguage.AR to "Ù„Ø§ ÙŠÙˆØ¬Ø¯ Ù†ØªØ§Ø¦Ø¬ ØªØ·Ø§Ø¨Ù‚ Ø§Ù„Ø¨Ø­Ø«", AppLanguage.EN to "No results match search"),
        "add_new_customer" to mapOf(AppLanguage.AR to "Ø¥Ø¶Ø§ÙØ© Ø¹Ù…ÙŠÙ„ Ø¬Ø¯ÙŠØ¯", AppLanguage.EN to "Add New Customer"),
        "cant_open_whatsapp" to mapOf(AppLanguage.AR to "ØªØ¹Ø°Ø± ÙØªØ­ ØªØ·Ø¨ÙŠÙ‚ ÙˆØ§ØªØ³Ø§Ø¨", AppLanguage.EN to "Could not open WhatsApp"),
        "delete_product_confirm" to mapOf(AppLanguage.AR to "Ù‡Ù„ Ø£Ù†Øª Ù…ØªØ£ÙƒØ¯ Ù…Ù† Ø±ØºØ¨ØªÙƒ ÙÙŠ Ø­Ø°Ù Ù‡Ø°Ø§ Ø§Ù„Ø¨Ù†Ø¯ØŸ", AppLanguage.EN to "Are you sure you want to delete this item?"),
        "delete_product_error" to mapOf(AppLanguage.AR to "ØªØ¹Ø°Ø± Ø­Ø°Ù Ø§Ù„Ø¨Ù†Ø¯.", AppLanguage.EN to "Could not delete item."),
        "choose_product_doc" to mapOf(AppLanguage.AR to "Ø§Ø®ØªØ± Ù…Ù†ØªØ¬Ù‹Ø§ Ø£Ùˆ Ø®Ø¯Ù…Ø© Ù„Ø¥Ø¶Ø§ÙØªÙ‡Ø§ Ù„Ù„Ù…Ø³ØªÙ†Ø¯", AppLanguage.EN to "Select a product or service to add to the document"),
        "no_products_available" to mapOf(AppLanguage.AR to "Ù„Ø§ ØªÙˆØ¬Ø¯ Ù…Ù†ØªØ¬Ø§Øª Ø£Ùˆ Ø®Ø¯Ù…Ø§Øª Ù…ØªÙˆÙØ±Ø©", AppLanguage.EN to "No products or services available"),
        "add_new_product" to mapOf(AppLanguage.AR to "Ø¥Ø¶Ø§ÙØ© Ø¨Ù†Ø¯ Ø¬Ø¯ÙŠØ¯", AppLanguage.EN to "Add New Item"),
        "available_stock" to mapOf(AppLanguage.AR to "Ø§Ù„ÙƒÙ…ÙŠØ© Ø§Ù„Ù…ØªØ§Ø­Ø©: ", AppLanguage.EN to "Available stock: "),
        "cant_delete_doc" to mapOf(AppLanguage.AR to "ØªØ¹Ø°Ø± Ø­Ø°Ù Ø§Ù„Ù…Ø³ØªÙ†Ø¯ Ø­Ø§Ù„ÙŠØ§Ù‹", AppLanguage.EN to "Could not delete document currently"),
        "filter_all" to mapOf(AppLanguage.AR to "Ø§Ù„ÙƒÙ„", AppLanguage.EN to "All"),
        "filter_unpaid" to mapOf(AppLanguage.AR to "ØºÙŠØ± Ù…Ø¯ÙÙˆØ¹Ø©", AppLanguage.EN to "Unpaid"),
        "customer_active" to mapOf(AppLanguage.AR to "Ù†Ø´Ø·", AppLanguage.EN to "Active"),
        "filter_paid" to mapOf(AppLanguage.AR to "Ù…Ø¯ÙÙˆØ¹Ø©", AppLanguage.EN to "Paid"),
        "filter_partial" to mapOf(AppLanguage.AR to "Ø¬Ø²Ø¦ÙŠØ©", AppLanguage.EN to "Partial"),
        "filter_latest" to mapOf(AppLanguage.AR to "Ø§Ù„Ø£Ø­Ø¯Ø«", AppLanguage.EN to "Latest"),
        "delete_doc_title" to mapOf(AppLanguage.AR to "Ø­Ø°Ù Ø§Ù„Ù…Ø³ØªÙ†Ø¯", AppLanguage.EN to "Delete Document"),
        "delete_doc_confirm" to mapOf(AppLanguage.AR to "Ù‡Ù„ ØªØ±ÙŠØ¯ Ø­Ø°Ù Ù‡Ø°Ø§ Ø§Ù„Ù…Ø³ØªÙ†Ø¯ØŸ Ù„Ø§ ÙŠÙ…ÙƒÙ† Ø§Ù„ØªØ±Ø§Ø¬Ø¹ Ø¹Ù† Ù‡Ø°Ø§ Ø§Ù„Ø¥Ø¬Ø±Ø§Ø¡.", AppLanguage.EN to "Do you want to delete this document? This action cannot be undone."),
        "edit_customer" to mapOf(AppLanguage.AR to "ØªØ¹Ø¯ÙŠÙ„ Ø§Ù„Ø¹Ù…ÙŠÙ„", AppLanguage.EN to "Edit Customer"),
        "save_customer_error" to mapOf(AppLanguage.AR to "ØªØ¹Ø°Ø± Ø­ÙØ¸ Ø§Ù„Ø¹Ù…ÙŠÙ„. ØªØ­Ù‚Ù‚ Ù…Ù† Ø§Ù„Ø¨ÙŠØ§Ù†Ø§Øª ÙˆØ­Ø§ÙˆÙ„ Ù…Ø±Ø© Ø£Ø®Ø±Ù‰.", AppLanguage.EN to "Could not save customer. Check data and try again."),
        "edit_product" to mapOf(AppLanguage.AR to "ØªØ¹Ø¯ÙŠÙ„ Ø§Ù„Ø¨Ù†Ø¯", AppLanguage.EN to "Edit Item"),
        "save_product_error" to mapOf(AppLanguage.AR to "ØªØ¹Ø°Ø± Ø­ÙØ¸ Ø§Ù„Ù…Ù†ØªØ¬ Ø£Ùˆ Ø§Ù„Ø®Ø¯Ù…Ø©. ØªØ­Ù‚Ù‚ Ù…Ù† Ø§Ù„Ø¨ÙŠØ§Ù†Ø§Øª ÙˆØ­Ø§ÙˆÙ„ Ù…Ø±Ø© Ø£Ø®Ø±Ù‰.", AppLanguage.EN to "Could not save product or service. Check data and try again."),
        "save_settings_error" to mapOf(AppLanguage.AR to "ØªØ¹Ø°Ø± Ø­ÙØ¸ Ø¥Ø¹Ø¯Ø§Ø¯Ø§Øª Ø§Ù„Ù…ØªØ¬Ø±. Ø­Ø§ÙˆÙ„ Ù…Ø±Ø© Ø£Ø®Ø±Ù‰.", AppLanguage.EN to "Could not save business settings. Try again."),
        "settings" to mapOf(AppLanguage.AR to "Ø§Ù„Ø¥Ø¹Ø¯Ø§Ø¯Ø§Øª", AppLanguage.EN to "Settings"),
        "invoice_notes" to mapOf(AppLanguage.AR to "Ù…Ù„Ø§Ø­Ø¸Ø§Øª Ø¥Ø¶Ø§ÙÙŠØ©", AppLanguage.EN to "Additional Notes"),
        
        // AI dialects, platforms, tones
        "ai_inquiry" to mapOf(AppLanguage.AR to "Ø§Ø³ØªÙØ³Ø§Ø±", AppLanguage.EN to "Inquiry"),
        "ai_objection" to mapOf(AppLanguage.AR to "Ø§Ø¹ØªØ±Ø§Ø¶", AppLanguage.EN to "Objection"),
        "ai_greeting" to mapOf(AppLanguage.AR to "ØªØ±Ø­ÙŠØ¨", AppLanguage.EN to "Greeting"),
        "ai_gulf" to mapOf(AppLanguage.AR to "Ø®Ù„ÙŠØ¬ÙŠØ©", AppLanguage.EN to "Gulf"),
        "ai_yemeni" to mapOf(AppLanguage.AR to "ÙŠÙ…Ù†ÙŠ", AppLanguage.EN to "Yemeni"),
        "ai_fusha_simple" to mapOf(AppLanguage.AR to "ÙØµØ­Ù‰ Ø¨Ø³ÙŠØ·Ø©", AppLanguage.EN to "Simple MSA"),
        "ai_egyptian" to mapOf(AppLanguage.AR to "Ù…ØµØ±ÙŠØ©", AppLanguage.EN to "Egyptian"),
        "ai_standard" to mapOf(AppLanguage.AR to "ÙØµØ­Ù‰", AppLanguage.EN to "Standard"),
        "ai_notes_label" to mapOf(AppLanguage.AR to "Ù…Ù„Ø§Ø­Ø¸Ø§Øª Ø¥Ø¶Ø§ÙÙŠØ© Ø£Ùˆ Ù…Ø¹Ù„ÙˆÙ…Ø§Øª ÙˆØªÙØ§ØµÙŠÙ„", AppLanguage.EN to "Additional notes or details"),
        "ai_instagram" to mapOf(AppLanguage.AR to "Ø¥Ù†Ø³ØªØºØ±Ø§Ù…", AppLanguage.EN to "Instagram"),
        "ai_twitter" to mapOf(AppLanguage.AR to "ØªÙˆÙŠØªØ±", AppLanguage.EN to "Twitter"),
        "ai_facebook" to mapOf(AppLanguage.AR to "ÙÙŠØ³Ø¨ÙˆÙƒ", AppLanguage.EN to "Facebook"),
        "ai_offer_label" to mapOf(AppLanguage.AR to "Ø§Ù„Ø¹Ø±Ø¶ Ø§Ù„Ø®Ø§Øµ (Ø§Ø®ØªÙŠØ§Ø±ÙŠ)", AppLanguage.EN to "Special offer (optional)"),
        "ai_notes_simple" to mapOf(AppLanguage.AR to "Ù…Ù„Ø§Ø­Ø¸Ø§Øª Ø¥Ø¶Ø§ÙÙŠØ©", AppLanguage.EN to "Additional notes"),
        "ai_reply_settings" to mapOf(AppLanguage.AR to "Ø¥Ø¹Ø¯Ø§Ø¯Ø§Øª Ø§Ù„Ø±Ø¯ Ø§Ù„Ø°ÙƒÙŠ", AppLanguage.EN to "Smart Reply Settings"),
        "ai_caption_settings" to mapOf(AppLanguage.AR to "Ø¥Ø¹Ø¯Ø§Ø¯Ø§Øª ÙƒØ§Ø¨Ø´Ù† Ù…Ù†ØµØ§Øª Ø§Ù„ØªÙˆØ§ØµÙ„", AppLanguage.EN to "Social Media Caption Settings"),
        "ai_case_type" to mapOf(AppLanguage.AR to "Ù†ÙˆØ¹ Ø§Ù„Ø­Ø§Ù„Ø©", AppLanguage.EN to "Case Type"),
        "ai_dialect" to mapOf(AppLanguage.AR to "Ø§Ù„Ù„Ù‡Ø¬Ø©", AppLanguage.EN to "Dialect"),
        "ai_tone" to mapOf(AppLanguage.AR to "Ø§Ù„Ø£Ø³Ù„ÙˆØ¨", AppLanguage.EN to "Tone"),
        "ai_platform" to mapOf(AppLanguage.AR to "Ø§Ù„Ù…Ù†ØµØ©", AppLanguage.EN to "Platform"),
        "ai_case_price_request" to mapOf(AppLanguage.AR to "Ø·Ù„Ø¨ Ø³Ø¹Ø±", AppLanguage.EN to "Price request"),
        "ai_case_price_objection" to mapOf(AppLanguage.AR to "Ø§Ù„Ø³Ø¹Ø± ØºØ§Ù„ÙŠ", AppLanguage.EN to "Price objection"),
        "ai_case_discount_request" to mapOf(AppLanguage.AR to "ÙŠØ±ÙŠØ¯ Ø®ØµÙ…", AppLanguage.EN to "Discount request"),
        "ai_case_delivery_question" to mapOf(AppLanguage.AR to "Ø³Ø¤Ø§Ù„ Ø¹Ù† Ø§Ù„ØªÙˆØµÙŠÙ„", AppLanguage.EN to "Delivery question"),
        "ai_case_availability_question" to mapOf(AppLanguage.AR to "Ø³Ø¤Ø§Ù„ Ø¹Ù† Ø§Ù„ØªÙˆÙØ±", AppLanguage.EN to "Availability question"),
        "ai_case_customer_hesitant" to mapOf(AppLanguage.AR to "Ø¹Ù…ÙŠÙ„ Ù…ØªØ±Ø¯Ø¯", AppLanguage.EN to "Hesitant customer"),
        "ai_case_customer_interested" to mapOf(AppLanguage.AR to "Ø¹Ù…ÙŠÙ„ Ù…Ù‡ØªÙ…", AppLanguage.EN to "Interested customer"),
        "ai_case_follow_up" to mapOf(AppLanguage.AR to "Ù…ØªØ§Ø¨Ø¹Ø© Ø¹Ù…ÙŠÙ„", AppLanguage.EN to "Follow up"),
        "ai_case_payment_reminder" to mapOf(AppLanguage.AR to "ØªØ°ÙƒÙŠØ± Ø¨Ø§Ù„Ø¯ÙØ¹", AppLanguage.EN to "Payment reminder"),
        "ai_case_delayed_apology" to mapOf(AppLanguage.AR to "Ø§Ø¹ØªØ°Ø§Ø± Ø¹Ù† Ø§Ù„ØªØ£Ø®Ø±", AppLanguage.EN to "Delayed response apology"),
        "ai_case_review_request" to mapOf(AppLanguage.AR to "Ø·Ù„Ø¨ ØªÙ‚ÙŠÙŠÙ…", AppLanguage.EN to "Review request"),
        "ai_case_general_inquiry" to mapOf(AppLanguage.AR to "Ø§Ø³ØªÙØ³Ø§Ø± Ø¹Ø§Ù…", AppLanguage.EN to "General inquiry"),
        "ai_tone_premium" to mapOf(AppLanguage.AR to "ÙØ§Ø®Ø±", AppLanguage.EN to "Premium"),
        "ai_case_price_request_label" to mapOf(AppLanguage.AR to "Ø·Ù„Ø¨ Ø³Ø¹Ø±", AppLanguage.EN to "Price request"),
        "ai_tone_label" to mapOf(AppLanguage.AR to "Ø§Ù„Ø£Ø³Ù„ÙˆØ¨", AppLanguage.EN to "Tone"),
        "ai_audience_label" to mapOf(AppLanguage.AR to "Ù†ÙˆØ¹ Ø§Ù„Ø¬Ù…Ù‡ÙˆØ±", AppLanguage.EN to "Audience type"),
        "ai_settings_reply_title" to mapOf(AppLanguage.AR to "Ø¥Ø¹Ø¯Ø§Ø¯Ø§Øª Ø§Ù„Ø±Ø¯ Ø§Ù„Ø°ÙƒÙŠ", AppLanguage.EN to "Smart Reply Settings"),
        "ai_settings_caption_title" to mapOf(AppLanguage.AR to "Ø¥Ø¹Ø¯Ø§Ø¯Ø§Øª Ø§Ù„ÙƒØ§Ø¨Ø´Ù† Ø§Ù„Ø°ÙƒÙŠ", AppLanguage.EN to "Smart Caption Settings"),
        "ai_reply_preview_title" to mapOf(AppLanguage.AR to "Ù…Ø¹Ø§ÙŠÙ†Ø© Ø§Ù„Ø±Ø¯", AppLanguage.EN to "Reply Preview"),
        "ai_caption_preview_title" to mapOf(AppLanguage.AR to "Ù…Ø¹Ø§ÙŠÙ†Ø© Ø§Ù„ÙƒØ§Ø¨Ø´Ù†", AppLanguage.EN to "Caption Preview"),
        "ai_report" to mapOf(AppLanguage.AR to "Ø§Ù„Ø¥Ø¨Ù„Ø§Øº Ø¹Ù† Ù‡Ø°Ø§ Ø§Ù„Ù…Ø­ØªÙˆÙ‰", AppLanguage.EN to "Report this content"),
        "privacy_policy" to mapOf(AppLanguage.AR to "Ø³ÙŠØ§Ø³Ø© Ø§Ù„Ø®ØµÙˆØµÙŠØ©", AppLanguage.EN to "Privacy Policy"),
        "ai_cust_name_opt" to mapOf(AppLanguage.AR to "Ø§Ø³Ù… Ø§Ù„Ø¹Ù…ÙŠÙ„ (Ø§Ø®ØªÙŠØ§Ø±ÙŠ)", AppLanguage.EN to "Customer name (optional)"),
        "ai_cust_msg_opt" to mapOf(AppLanguage.AR to "Ø±Ø³Ø§Ù„Ø© Ø§Ù„Ø²Ø¨ÙˆÙ† (Ø§Ø®ØªÙŠØ§Ø±ÙŠ)", AppLanguage.EN to "Customer message (optional)"),
        "ai_prod_srv_label" to mapOf(AppLanguage.AR to "Ø§Ù„Ù…Ù†ØªØ¬ Ø£Ùˆ Ø§Ù„Ø®Ø¯Ù…Ø©", AppLanguage.EN to "Product or Service"),
        "ai_add_image_opt" to mapOf(AppLanguage.AR to "Ø¥Ø¶Ø§ÙØ© ØµÙˆØ±Ø© Ø§Ù„Ù…Ù†ØªØ¬ (Ø§Ø®ØªÙŠØ§Ø±ÙŠ)", AppLanguage.EN to "Add product image (optional)"),
        "ai_selected_image" to mapOf(AppLanguage.AR to "ØªÙ… Ø§Ø®ØªÙŠØ§Ø± ØµÙˆØ±Ø© Ø§Ù„Ù…Ù†ØªØ¬", AppLanguage.EN to "Product image selected"),
        "ai_image_read_error" to mapOf(AppLanguage.AR to "ØªØ¹Ø°Ø± Ù‚Ø±Ø§Ø¡Ø© ØµÙˆØ±Ø© Ø§Ù„Ù…Ù†ØªØ¬.", AppLanguage.EN to "Could not read the product image."),
        "ai_limit_reached" to mapOf(AppLanguage.AR to "Ù„Ù‚Ø¯ Ø§Ø³ØªÙ‡Ù„ÙƒØª ÙƒØ§Ù…Ù„ Ø§Ù„Ø­Ø¯ Ø§Ù„Ù…ØªØ§Ø­ Ù„Ùƒ Ù…Ù† Ø§Ø³ØªØ¹Ù„Ø§Ù…Ø§Øª Ø§Ù„Ø°ÙƒØ§Ø¡ Ø§Ù„Ø§ØµØ·Ù†Ø§Ø¹ÙŠ Ù„Ø´Ù‡Ø±Ùƒ Ø§Ù„Ø­Ø§Ù„ÙŠ. ÙŠØ±Ø¬Ù‰ Ø§Ù„ØªØ±Ù‚ÙŠØ© Ù„Ù„Ø§Ø³ØªÙ…Ø±Ø§Ø±.", AppLanguage.EN to "You have used all available AI requests for this month. Please upgrade to continue."),
        "ai_remove_image" to mapOf(AppLanguage.AR to "Ø¥Ø²Ø§Ù„Ø© Ø§Ù„ØµÙˆØ±Ø©", AppLanguage.EN to "Remove image"),
        "ai_btn_gen_caption" to mapOf(AppLanguage.AR to "ØªÙˆÙ„ÙŠØ¯ Ø§Ù„ÙƒØ§Ø¨Ø´Ù†", AppLanguage.EN to "Generate Caption"),
        "ai_tone_friendly" to mapOf(AppLanguage.AR to "ÙˆØ¯ÙŠ", AppLanguage.EN to "Friendly"),
        "ai_tone_formal" to mapOf(AppLanguage.AR to "Ø±Ø³Ù…ÙŠ", AppLanguage.EN to "Formal"),
        "ai_tone_sales" to mapOf(AppLanguage.AR to "ØªØ³ÙˆÙŠÙ‚ÙŠ", AppLanguage.EN to "Sales"),
        "ai_tone_funny" to mapOf(AppLanguage.AR to "Ù…Ø±Ø­", AppLanguage.EN to "Funny"),
        "complete_settings_logo" to mapOf(AppLanguage.AR to "Ø£ÙƒÙ…Ù„ Ø¥Ø¹Ø¯Ø§Ø¯Ø§Øª Ø§Ù„Ù…ØªØ¬Ø± Ø£ÙˆÙ„Ø§Ù‹ Ù‚Ø¨Ù„ Ø±ÙØ¹ Ø§Ù„Ø´Ø¹Ø§Ø±", AppLanguage.EN to "Please complete store settings first before uploading logo"),
        "logo_saved_success" to mapOf(AppLanguage.AR to "ØªÙ… Ø­ÙØ¸ Ø´Ø¹Ø§Ø± Ø§Ù„Ù…ØªØ¬Ø± Ø¨Ù†Ø¬Ø§Ø­", AppLanguage.EN to "Store logo saved successfully"),
        "logo_upload_error" to mapOf(AppLanguage.AR to "ØªØ¹Ø°Ø± Ø±ÙØ¹ Ø§Ù„Ø´Ø¹Ø§Ø±. Ø­Ø§ÙˆÙ„ Ù…Ø±Ø© Ø£Ø®Ø±Ù‰.", AppLanguage.EN to "Could not upload logo. Try again."),
        "settings_saved_success" to mapOf(AppLanguage.AR to "ØªÙ… Ø­ÙØ¸ ØªØºÙŠÙŠØ±Ø§Øª Ø§Ù„Ù…ØªØ¬Ø± Ø¨Ù†Ø¬Ø§Ø­", AppLanguage.EN to "Store settings saved successfully"),
        "btn_save_store_changes" to mapOf(AppLanguage.AR to "Ø­ÙØ¸ ØªØºÙŠÙŠØ±Ø§Øª Ø§Ù„Ù…ØªØ¬Ø±", AppLanguage.EN to "Save store changes"),
        "logo_format_error" to mapOf(AppLanguage.AR to "Ø§Ø±ÙØ¹ ØµÙˆØ±Ø© Ø¨ØµÙŠØºØ© PNG Ø£Ùˆ JPG Ø£Ùˆ WebP.", AppLanguage.EN to "Please upload an image in PNG, JPG, or WebP format."),
        "logo_empty_error" to mapOf(AppLanguage.AR to "Ù…Ù„Ù Ø§Ù„Ø´Ø¹Ø§Ø± ÙØ§Ø±Øº.", AppLanguage.EN to "Logo file is empty."),
        "tab_store_account" to mapOf(AppLanguage.AR to "Ø­Ø³Ø§Ø¨ Ø§Ù„Ù…ØªØ¬Ø±", AppLanguage.EN to "Store Account"),
        "tab_personal_account" to mapOf(AppLanguage.AR to "Ø§Ù„Ø­Ø³Ø§Ø¨ Ø§Ù„Ø´Ø®ØµÙŠ", AppLanguage.EN to "Personal Account"),
        "product_image_format_error" to mapOf(AppLanguage.AR to "Ø§Ø±ÙØ¹ ØµÙˆØ±Ø© Ø¨ØµÙŠØºØ© PNG Ø£Ùˆ JPG Ø£Ùˆ WebP.", AppLanguage.EN to "Please upload a product image in PNG, JPG, or WebP format."),
        "image_empty_error" to mapOf(AppLanguage.AR to "Ù…Ù„Ù Ø§Ù„ØµÙˆØ±Ø© ÙØ§Ø±Øº.", AppLanguage.EN to "The image file is empty."),
        "image_size_error" to mapOf(AppLanguage.AR to "Ø­Ø¬Ù… ØµÙˆØ±Ø© Ø§Ù„Ù…Ù†ØªØ¬ ÙŠØ¬Ø¨ Ø£Ù„Ø§ ÙŠØªØ¬Ø§ÙˆØ² 1MB.", AppLanguage.EN to "Product image size must not exceed 1MB."),
        "change_password" to mapOf(AppLanguage.AR to "ØªØºÙŠÙŠØ± ÙƒÙ„Ù…Ø© Ø§Ù„Ù…Ø±ÙˆØ±", AppLanguage.EN to "Change Password"),
        "sending_password_link" to mapOf(AppLanguage.AR to "Ø¬Ø§Ø±ÙŠ Ø¥Ø±Ø³Ø§Ù„ Ø§Ù„Ø±Ø§Ø¨Ø·...", AppLanguage.EN to "Sending link..."),
        "password_reset_link_sent" to mapOf(AppLanguage.AR to "ØªÙ… Ø¥Ø±Ø³Ø§Ù„ Ø±Ø§Ø¨Ø· ØªØºÙŠÙŠØ± ÙƒÙ„Ù…Ø© Ø§Ù„Ù…Ø±ÙˆØ± Ø¥Ù„Ù‰ Ø¨Ø±ÙŠØ¯Ùƒ.", AppLanguage.EN to "Password reset link sent to your email."),
        "password_reset_link_failed" to mapOf(AppLanguage.AR to "ØªØ¹Ø°Ø± Ø¥Ø±Ø³Ø§Ù„ Ø±Ø§Ø¨Ø· ØªØºÙŠÙŠØ± ÙƒÙ„Ù…Ø© Ø§Ù„Ù…Ø±ÙˆØ±. Ø­Ø§ÙˆÙ„ Ù…Ø±Ø© Ø£Ø®Ø±Ù‰.", AppLanguage.EN to "Could not send the password reset link. Try again."),
        "edit_name" to mapOf(AppLanguage.AR to "ØªØ¹Ø¯ÙŠÙ„ Ø§Ù„Ø§Ø³Ù…", AppLanguage.EN to "Edit Name"),
        "edit_name_desc" to mapOf(AppLanguage.AR to "Ø¹Ø¯Ù‘Ù„ Ø§Ù„Ø§Ø³Ù… Ø§Ù„Ø¸Ø§Ù‡Ø± ÙÙŠ Ø§Ù„Ø­Ø³Ø§Ø¨ Ø«Ù… Ø§Ø­ÙØ¸Ù‡.", AppLanguage.EN to "Update the displayed account name and save it."),
        "edit_name_label" to mapOf(AppLanguage.AR to "Ø§Ù„Ø§Ø³Ù… Ø§Ù„Ø­Ø§Ù„ÙŠ", AppLanguage.EN to "Current Name"),
        "edit_name_invalid" to mapOf(AppLanguage.AR to "Ø§Ù„Ø§Ø³Ù… ÙŠØ¬Ø¨ Ø£Ù† ÙŠÙƒÙˆÙ† Ø¨ÙŠÙ† Ø­Ø±ÙÙŠÙ† Ùˆ80 Ø­Ø±ÙÙ‹Ø§.", AppLanguage.EN to "The name must be between 2 and 80 characters."),
        "name_updated" to mapOf(AppLanguage.AR to "ØªÙ… ØªØ­Ø¯ÙŠØ« Ø§Ù„Ø§Ø³Ù… Ø¨Ù†Ø¬Ø§Ø­.", AppLanguage.EN to "Name updated successfully."),
        "name_update_failed" to mapOf(AppLanguage.AR to "ØªØ¹Ø°Ø± ØªØ­Ø¯ÙŠØ« Ø§Ù„Ø§Ø³Ù… Ø§Ù„Ø¢Ù†.", AppLanguage.EN to "Could not update the name right now."),
        "saving" to mapOf(AppLanguage.AR to "Ø¬Ø§Ø±Ù Ø§Ù„Ø­ÙØ¸...", AppLanguage.EN to "Saving..."),
        "logout" to mapOf(AppLanguage.AR to "ØªØ³Ø¬ÙŠÙ„ Ø§Ù„Ø®Ø±ÙˆØ¬", AppLanguage.EN to "Logout"),
        "of" to mapOf(AppLanguage.AR to "Ù…Ù†", AppLanguage.EN to "of"),
        "generated_suggestions" to mapOf(AppLanguage.AR to "Ø§Ù„Ø§Ù‚ØªØ±Ø§Ø­Ø§Øª Ø§Ù„Ù…ÙˆÙ„Ø¯Ø©", AppLanguage.EN to "Generated Suggestions"),
        "variant_format" to mapOf(AppLanguage.AR to "ØµÙŠØºØ©: %s", AppLanguage.EN to "Format: %s"),
        "reply_copied" to mapOf(AppLanguage.AR to "ØªÙ… Ù†Ø³Ø® Ø§Ù„Ø±Ø¯ Ø¨Ù†Ø¬Ø§Ø­", AppLanguage.EN to "Reply copied successfully"),
        "copy" to mapOf(AppLanguage.AR to "Ù†Ø³Ø®", AppLanguage.EN to "Copy"),
        "caption_copied" to mapOf(AppLanguage.AR to "ØªÙ… Ù†Ø³Ø® Ø§Ù„ÙƒØ§Ø¨Ø´Ù† Ø¨Ù†Ø¬Ø§Ø­", AppLanguage.EN to "Caption copied successfully"),
        "unexpected_error" to mapOf(AppLanguage.AR to "Ø­Ø¯Ø« Ø®Ø·Ø£ ØºÙŠØ± Ù…ØªÙˆÙ‚Ø¹", AppLanguage.EN to "An unexpected error occurred"),
        "delete_account" to mapOf(AppLanguage.AR to "Ø­Ø°Ù Ø§Ù„Ø­Ø³Ø§Ø¨", AppLanguage.EN to "Delete Account"),
        "delete_account_desc" to mapOf(AppLanguage.AR to "Ø³ÙŠØªÙ… Ø­Ø°Ù Ø­Ø³Ø§Ø¨Ùƒ ÙˆØ¨ÙŠØ§Ù†Ø§ØªÙƒ Ø§Ù„Ù…Ø­Ù„ÙŠØ©ØŒ ÙˆÙ‚Ø¯ ØªØ­ØªØ§Ø¬ Ø¥Ù„Ù‰ Ø¥Ø¹Ø§Ø¯Ø© Ø§Ù„ØªØ³Ø¬ÙŠÙ„ Ù„Ù„ÙˆØµÙˆÙ„ Ù…Ø±Ø© Ø£Ø®Ø±Ù‰.", AppLanguage.EN to "Your account and local data will be deleted, and you may need to register again to access it."),
        "btn_cancel" to mapOf(AppLanguage.AR to "Ø¥Ù„ØºØ§Ø¡", AppLanguage.EN to "Cancel"),
        "account_delete_failed" to mapOf(AppLanguage.AR to "ØªØ¹Ø°Ø± Ø­Ø°Ù Ø§Ù„Ø­Ø³Ø§Ø¨ Ø§Ù„Ø¢Ù†.", AppLanguage.EN to "Could not delete the account right now."),
        "app_settings" to mapOf(AppLanguage.AR to "Ø¥Ø¹Ø¯Ø§Ø¯Ø§Øª Ø§Ù„ØªØ·Ø¨ÙŠÙ‚", AppLanguage.EN to "App Settings"),
        "store_logo" to mapOf(AppLanguage.AR to "Ø´Ø¹Ø§Ø± Ø§Ù„Ù…ØªØ¬Ø±", AppLanguage.EN to "Store Logo"),
        "personal_account_desc" to mapOf(AppLanguage.AR to "Ù…Ø±Ø­Ø¨Ø§Ù‹ Ø¨ÙƒØŒ Ø¥Ø¯Ø§Ø±Ø© Ø­Ø³Ø§Ø¨Ùƒ ÙˆÙ…Ø¹Ù„ÙˆÙ…Ø§ØªÙƒ Ø§Ù„Ø´Ø®ØµÙŠØ© ÙÙŠ Ù…ÙƒØ§Ù† Ø¢Ù…Ù†.", AppLanguage.EN to "Welcome, manage your account and personal info in a secure place."),
        "personal_account" to mapOf(AppLanguage.AR to "Ø­Ø³Ø§Ø¨ Ø´Ø®ØµÙŠ", AppLanguage.EN to "Personal Account"),
        "account_info" to mapOf(AppLanguage.AR to "Ù…Ø¹Ù„ÙˆÙ…Ø§Øª Ø§Ù„Ø­Ø³Ø§Ø¨", AppLanguage.EN to "Account Information"),
        "update_password_desc" to mapOf(AppLanguage.AR to "Ù‚Ù… Ø¨ØªØ­Ø¯ÙŠØ« ÙƒÙ„Ù…Ø© Ø§Ù„Ù…Ø±ÙˆØ± Ø§Ù„Ø®Ø§ØµØ© Ø¨Ø­Ø³Ø§Ø¨Ùƒ", AppLanguage.EN to "Update your account password"),
        "unknown_user" to mapOf(AppLanguage.AR to "Ù…Ø³ØªØ®Ø¯Ù…", AppLanguage.EN to "User"),
        "logout_desc" to mapOf(AppLanguage.AR to "ØªØ³Ø¬ÙŠÙ„ Ø§Ù„Ø®Ø±ÙˆØ¬ Ù…Ù† Ø§Ù„ØªØ·Ø¨ÙŠÙ‚ Ø§Ù„Ø­Ø§Ù„ÙŠ", AppLanguage.EN to "Sign out of the current application"),
        "verified_store" to mapOf(AppLanguage.AR to "Ù…ØªØ¬Ø± Ù…ÙˆØ«Ù‚", AppLanguage.EN to "Verified Store"),
        "store_slogan" to mapOf(AppLanguage.AR to "Ø£Ø¯ÙˆØ§Øª Ø°ÙƒÙŠØ© Ù„ØªØ¬Ø§Ø±ØªÙƒ Ø§Ù„ÙŠÙˆÙ…ÙŠØ©", AppLanguage.EN to "Smart tools for your daily business"),
        "business_category" to mapOf(AppLanguage.AR to "ØªØµÙ†ÙŠÙ Ø§Ù„Ù†Ø´Ø§Ø· Ø§Ù„ØªØ¬Ø§Ø±ÙŠ", AppLanguage.EN to "Business Category"),
        "contact_phone" to mapOf(AppLanguage.AR to "Ø±Ù‚Ù… Ø§Ù„ØªÙˆØ§ØµÙ„", AppLanguage.EN to "Contact Phone"),
        "invoice_notifications_prefs" to mapOf(AppLanguage.AR to "ØªÙØ¶ÙŠÙ„Ø§Øª Ø§Ù„ÙÙˆØ§ØªÙŠØ± ÙˆØ§Ù„Ø¥Ø´Ø¹Ø§Ø±Ø§Øª", AppLanguage.EN to "Invoice & Notification Preferences"),
        "billing_prefs_value" to mapOf(AppLanguage.AR to "Ø¨Ø±ÙŠØ¯ Ø¥Ù„ÙƒØªØ±ÙˆÙ†ÙŠØŒ Ø¥Ø´Ø¹Ø§Ø±Ø§Øª Ø¯Ø§Ø®Ù„ Ø§Ù„ØªØ·Ø¨ÙŠÙ‚", AppLanguage.EN to "Email, in-app notifications"),
        "save_store_changes" to mapOf(AppLanguage.AR to "Ø­ÙØ¸ ØªØºÙŠÙŠØ±Ø§Øª Ø§Ù„Ù…ØªØ¬Ø±", AppLanguage.EN to "Save Store Changes"),
        "category_default_value" to mapOf(AppLanguage.AR to "ØªÙˆÙÙŠØ±", AppLanguage.EN to "Tawfeer (Retail)"),
        "customers_desc" to mapOf(AppLanguage.AR to "Ø¥Ø¯Ø§Ø±Ø© Ø¹Ù„Ø§Ù‚Ø§ØªÙƒ ÙˆØªÙˆØ§ØµÙ„ Ù…Ø¹ Ø¹Ù…Ù„Ø§Ø¦Ùƒ Ø¨Ø³Ù‡ÙˆÙ„Ø©.", AppLanguage.EN to "Manage your relations and communicate with clients easily."),
        "total_customers" to mapOf(AppLanguage.AR to "Ø¥Ø¬Ù…Ø§Ù„ÙŠ Ø§Ù„Ø¹Ù…Ù„Ø§Ø¡", AppLanguage.EN to "Total Customers"),
        "active_customers" to mapOf(AppLanguage.AR to "Ø¹Ù…Ù„Ø§Ø¡ Ù†Ø´Ø·ÙŠÙ†", AppLanguage.EN to "Active Customers"),
        "new_customers" to mapOf(AppLanguage.AR to "Ø¹Ù…Ù„Ø§Ø¡ Ø¬Ø¯Ø¯", AppLanguage.EN to "New Customers"),
        "most_active_customers" to mapOf(AppLanguage.AR to "Ø£ÙƒØ«Ø± ØªØ¹Ø§Ù…Ù„Ø§Ù‹", AppLanguage.EN to "Top Customers"),
        "dark_mode_label" to mapOf(AppLanguage.AR to "Ø§Ù„ÙˆØ¶Ø¹ Ø§Ù„Ø¯Ø§ÙƒÙ†", AppLanguage.EN to "Dark Mode"),
        "light_mode_label" to mapOf(AppLanguage.AR to "Ø§Ù„ÙˆØ¶Ø¹ Ø§Ù„ÙØ§ØªØ­", AppLanguage.EN to "Light Mode"),
        "current_plan" to mapOf(AppLanguage.AR to "Ø§Ù„Ø®Ø·Ø© Ø§Ù„Ø­Ø§Ù„ÙŠØ©", AppLanguage.EN to "Current Plan"),
        "free_plan" to mapOf(AppLanguage.AR to "Ø§Ù„Ø®Ø·Ø© Ø§Ù„Ù…Ø¬Ø§Ù†ÙŠØ©", AppLanguage.EN to "Free Plan"),
        "starter_plan" to mapOf(AppLanguage.AR to "Ø®Ø·Ø© Ø§Ù„Ø¨Ø¯Ø§ÙŠØ©", AppLanguage.EN to "Starter Plan"),
        "ai_uses" to mapOf(AppLanguage.AR to "Ø§Ø³ØªØ®Ø¯Ø§Ù…Ø§Øª AI", AppLanguage.EN to "AI Uses"),
        "retry" to mapOf(AppLanguage.AR to "Ø¥Ø¹Ø§Ø¯Ø© Ø§Ù„Ù…Ø­Ø§ÙˆÙ„Ø©", AppLanguage.EN to "Retry"),
        "store_settings" to mapOf(AppLanguage.AR to "Ø¥Ø¹Ø¯Ø§Ø¯Ø§Øª Ø§Ù„Ù…ØªØ¬Ø±", AppLanguage.EN to "Store Settings"),
        "store_settings_desc" to mapOf(AppLanguage.AR to "Ø§Ù„Ø´Ø¹Ø§Ø±ØŒ Ø¨ÙŠØ§Ù†Ø§Øª Ø§Ù„Ù†Ø´Ø§Ø·ØŒ Ø§Ù„Ø¹Ù…Ù„Ø© ÙˆØ§Ù„Ø¯ÙˆÙ„Ø©", AppLanguage.EN to "Logo, business info, currency and country"),
        "account_settings" to mapOf(AppLanguage.AR to "Ø¥Ø¹Ø¯Ø§Ø¯Ø§Øª Ø§Ù„Ø­Ø³Ø§Ø¨", AppLanguage.EN to "Account Settings"),
        "account_settings_desc" to mapOf(AppLanguage.AR to "Ø§Ù„Ø¨Ø±ÙŠØ¯ØŒ ÙƒÙ„Ù…Ø© Ø§Ù„Ù…Ø±ÙˆØ±ØŒ Ø¨ÙŠØ§Ù†Ø§Øª Ø§Ù„Ø­Ø³Ø§Ø¨", AppLanguage.EN to "Email, password, account info"),
        "app_settings_desc" to mapOf(AppLanguage.AR to "Ø§Ù„Ù„ØºØ©ØŒ Ø§Ù„Ù…Ø¸Ù‡Ø±ØŒ ØªÙØ¶ÙŠÙ„Ø§Øª Ø§Ù„ØªØ·Ø¨ÙŠÙ‚", AppLanguage.EN to "Language, theme, app preferences"),
        "upgrade_plan" to mapOf(AppLanguage.AR to "ØªØ±Ù‚ÙŠØ© Ø§Ù„Ø®Ø·Ø©", AppLanguage.EN to "Upgrade Plan"),
        "upgrade_plan_desc" to mapOf(AppLanguage.AR to "Ø§ÙØªØ­ Ø­Ø¯ÙˆØ¯ Ø£Ø¹Ù„Ù‰ ÙˆÙ…ÙŠØ²Ø§Øª Ø§Ø­ØªØ±Ø§ÙÙŠØ©", AppLanguage.EN to "Unlock higher limits and pro features"),
        "rise_to_pro" to mapOf(AppLanguage.AR to "Ø§Ø±ØªÙ‚ Ø¨ØªØ¬Ø§Ø±ÙŠÙˆ Ø¨Ø±Ùˆ", AppLanguage.EN to "Upgrade to Tijario Pro"),
        "pro_benefits_desc" to mapOf(AppLanguage.AR to "Ø­Ø¯ÙˆØ¯ Ø£Ø¹Ù„Ù‰ Ù„Ù„Ù…Ø³ØªÙ†Ø¯Ø§Øª ÙˆØ§Ù„Ø°ÙƒØ§Ø¡ Ø§Ù„Ø§ØµØ·Ù†Ø§Ø¹ÙŠ ÙˆØªØ¬Ø±Ø¨Ø© Ø£Ø¹Ù…Ø§Ù„ Ø£ÙƒØ«Ø± Ø§Ø­ØªØ±Ø§ÙÙŠØ©.", AppLanguage.EN to "Higher limits for documents, AI, and a more professional business experience."),
        "coming_soon_upgrade" to mapOf(AppLanguage.AR to "Ù‚Ø±ÙŠØ¨Ù‹Ø§: ØªÙØ¹ÙŠÙ„ Ø§Ù„ØªØ±Ù‚ÙŠØ©", AppLanguage.EN to "Coming Soon: Activate Upgrade"),
        "documents" to mapOf(AppLanguage.AR to "Ø§Ù„Ù…Ø³ØªÙ†Ø¯Ø§Øª", AppLanguage.EN to "Documents"),
        "remaining" to mapOf(AppLanguage.AR to "Ø§Ù„Ù…ØªØ¨Ù‚ÙŠ: %s", AppLanguage.EN to "%s remaining"),
        "add_new_item" to mapOf(AppLanguage.AR to "Ø¥Ø¶Ø§ÙØ© Ø¨Ù†Ø¯ Ø¬Ø¯ÙŠØ¯", AppLanguage.EN to "Add New Item"),
        "suitable_growing_stores" to mapOf(AppLanguage.AR to "Ù…Ù†Ø§Ø³Ø¨ Ù„Ù„Ù…ØªØ§Ø¬Ø± Ø§Ù„Ù†Ø§Ù…ÙŠØ©", AppLanguage.EN to "Suitable for growing stores"),
        "business_lots_docs" to mapOf(AppLanguage.AR to "Ù„Ù„Ø£Ø¹Ù…Ø§Ù„ ÙƒØ«ÙŠØ±Ø© Ø§Ù„Ù…Ø³ØªÙ†Ø¯Ø§Øª", AppLanguage.EN to "For document-heavy businesses"),
        "more_monthly_docs" to mapOf(AppLanguage.AR to "Ù…Ø³ØªÙ†Ø¯Ø§Øª Ø´Ù‡Ø±ÙŠØ© Ø£ÙƒØ«Ø±", AppLanguage.EN to "More monthly documents"),
        "higher_ai_uses" to mapOf(AppLanguage.AR to "Ø§Ø³ØªØ®Ø¯Ø§Ù…Ø§Øª AI Ø£Ø¹Ù„Ù‰", AppLanguage.EN to "Higher AI limits"),
        "pro_pdf_templates" to mapOf(AppLanguage.AR to "Ù‚ÙˆØ§Ù„Ø¨ PDF Ø§Ø­ØªØ±Ø§ÙÙŠØ©", AppLanguage.EN to "Professional PDF templates"),
        "advanced_features_support" to mapOf(AppLanguage.AR to "Ø¯Ø¹Ù… Ù…ÙŠØ²Ø§Øª Ù…ØªÙ‚Ø¯Ù…Ø©", AppLanguage.EN to "Advanced features support"),
        "higher_limits" to mapOf(AppLanguage.AR to "Ø­Ø¯ÙˆØ¯ Ø£Ø¹Ù„Ù‰", AppLanguage.EN to "Higher limits"),
        "priority_features" to mapOf(AppLanguage.AR to "Ø£ÙˆÙ„ÙˆÙŠØ© ÙÙŠ Ø§Ù„Ù…ÙŠØ²Ø§Øª", AppLanguage.EN to "Priority features"),
        "more_flexible_management" to mapOf(AppLanguage.AR to "Ø¥Ø¯Ø§Ø±Ø© Ø£ÙƒØ«Ø± Ù…Ø±ÙˆÙ†Ø©", AppLanguage.EN to "More flexible management"),
        "ready_to_expand" to mapOf(AppLanguage.AR to "Ø¬Ø§Ù‡Ø² Ù„Ù„ØªÙˆØ³Ø¹", AppLanguage.EN to "Ready to scale"),
        "no_email_associated" to mapOf(AppLanguage.AR to "Ù„Ø§ ÙŠÙˆØ¬Ø¯ Ø¨Ø±ÙŠØ¯ Ø¥Ù„ÙƒØªØ±ÙˆÙ†ÙŠ Ù…Ø±ØªØ¨Ø· Ø¨Ø§Ù„Ø­Ø³Ø§Ø¨", AppLanguage.EN to "No email associated with this account"),
        "all_amounts_in" to mapOf(AppLanguage.AR to "Ø¬Ù…ÙŠØ¹ Ø§Ù„Ø£Ø±Ù‚Ø§Ù… Ø¨Ù€ %s", AppLanguage.EN to "All amounts in %s"),
        "total_sales" to mapOf(AppLanguage.AR to "Ø¥Ø¬Ù…Ø§Ù„ÙŠ Ø§Ù„Ù…Ø¨ÙŠØ¹Ø§Øª", AppLanguage.EN to "Total Sales"),
        "latest_documents" to mapOf(AppLanguage.AR to "Ø¢Ø®Ø± Ø§Ù„Ù…Ø³ØªÙ†Ø¯Ø§Øª", AppLanguage.EN to "Latest Documents"),
        "view_all" to mapOf(AppLanguage.AR to "Ø¹Ø±Ø¶ Ø§Ù„ÙƒÙ„", AppLanguage.EN to "View All"),
        "available_stock_optional" to mapOf(AppLanguage.AR to "Ø§Ù„ÙƒÙ…ÙŠØ© Ø§Ù„Ù…ØªÙˆÙØ±Ø© (Ø§Ø®ØªÙŠØ§Ø±ÙŠ)", AppLanguage.EN to "Available Quantity (Optional)"),
        "invoice_num" to mapOf(AppLanguage.AR to "ÙØ§ØªÙˆØ±Ø© %s", AppLanguage.EN to "Invoice %s"),
        "quote_num" to mapOf(AppLanguage.AR to "Ø¹Ø±Ø¶ Ø³Ø¹Ø± %s", AppLanguage.EN to "Quote %s"),
        "customer_label" to mapOf(AppLanguage.AR to "Ø§Ù„Ø¹Ù…ÙŠÙ„: %s", AppLanguage.EN to "Customer: %s"),
        "total_label" to mapOf(AppLanguage.AR to "Ø§Ù„Ø¥Ø¬Ù…Ø§Ù„ÙŠ: %s %s", AppLanguage.EN to "Total: %s %s"),
        "payment_status_label" to mapOf(AppLanguage.AR to "Ø­Ø§Ù„Ø© Ø§Ù„Ø¯ÙØ¹: %s", AppLanguage.EN to "Payment Status: %s"),
        "document_preview" to mapOf(AppLanguage.AR to "Ù…Ø¹Ø§ÙŠÙ†Ø© Ø£ÙˆÙ„ÙŠØ©", AppLanguage.EN to "Preview"),
        "invoice_language" to mapOf(AppLanguage.AR to "Ù„ØºØ© Ø§Ù„ÙØ§ØªÙˆØ±Ø©", AppLanguage.EN to "Invoice Language"),
        "templates" to mapOf(AppLanguage.AR to "Ø§Ù„Ù‚ÙˆØ§Ù„Ø¨", AppLanguage.EN to "Templates"),
        "from" to mapOf(AppLanguage.AR to "Ù…Ù†", AppLanguage.EN to "From"),
        "bill_to" to mapOf(AppLanguage.AR to "Ø¥Ù„Ù‰ (Ø§Ù„Ø¹Ù…ÙŠÙ„)", AppLanguage.EN to "Bill To"),
        "add_client" to mapOf(AppLanguage.AR to "Ø§Ø®ØªØ± Ø¹Ù…ÙŠÙ„", AppLanguage.EN to "Add Client"),
        "items_count" to mapOf(AppLanguage.AR to "Ø§Ù„Ø¨Ù†ÙˆØ¯ (%d)", AppLanguage.EN to "Items (%d)"),
        "subtotal" to mapOf(AppLanguage.AR to "Ø§Ù„Ø¥Ø¬Ù…Ø§Ù„ÙŠ Ø§Ù„ÙØ±Ø¹ÙŠ", AppLanguage.EN to "Subtotal"),
        "edit_item_title" to mapOf(AppLanguage.AR to "ØªØ¹Ø¯ÙŠÙ„ Ø¨Ù†Ø¯", AppLanguage.EN to "Edit Item"),
        "item_name_label" to mapOf(AppLanguage.AR to "Ø§Ø³Ù… Ø§Ù„Ø¨Ù†Ø¯", AppLanguage.EN to "Item Name"),
        "item_price_label" to mapOf(AppLanguage.AR to "Ø³Ø¹Ø± Ø§Ù„Ù…Ù†ØªØ¬", AppLanguage.EN to "Item Price"),
        "item_qty_label" to mapOf(AppLanguage.AR to "Ø§Ù„ÙƒÙ…ÙŠØ©", AppLanguage.EN to "Item Quantity"),
        "unit_measure_label" to mapOf(AppLanguage.AR to "ÙˆØ­Ø¯Ø© Ø§Ù„Ù‚ÙŠØ§Ø³", AppLanguage.EN to "Unit of Measure"),
        "unit_none" to mapOf(AppLanguage.AR to "Ù„Ø§ Ø´ÙŠØ¡", AppLanguage.EN to "None"),
        "item_discount" to mapOf(AppLanguage.AR to "Ø§Ù„Ø®ØµÙ…", AppLanguage.EN to "Discount"),
        "item_tax_rate" to mapOf(AppLanguage.AR to "Ù†Ø³Ø¨Ø© Ø§Ù„Ø¶Ø±ÙŠØ¨Ø©", AppLanguage.EN to "Tax Rate"),
        "amount_label" to mapOf(AppLanguage.AR to "Ø§Ù„Ø¥Ø¬Ù…Ø§Ù„ÙŠ", AppLanguage.EN to "Amount"),
        "item_desc_label" to mapOf(AppLanguage.AR to "Ø§Ù„ÙˆØµÙ", AppLanguage.EN to "Item Description"),
        "btn_preview" to mapOf(AppLanguage.AR to "Ù…Ø¹Ø§ÙŠÙ†Ø©", AppLanguage.EN to "Preview"),
        "btn_save" to mapOf(AppLanguage.AR to "Ø­ÙØ¸", AppLanguage.EN to "Save"),
        "created_on" to mapOf(AppLanguage.AR to "Ø£Ù†Ø´Ø¦Øª ÙÙŠ %s", AppLanguage.EN to "Created on %s"),
        "add_item" to mapOf(AppLanguage.AR to "Ø¥Ø¶Ø§ÙØ© Ø¨Ù†Ø¯", AppLanguage.EN to "Add Item"),
        "invoice_info_title" to mapOf(AppLanguage.AR to "Ø¨ÙŠØ§Ù†Ø§Øª Ø§Ù„ÙØ§ØªÙˆØ±Ø©", AppLanguage.EN to "Invoice Info"),
        "invoice_number" to mapOf(AppLanguage.AR to "Ø±Ù‚Ù… Ø§Ù„ÙØ§ØªÙˆØ±Ø©", AppLanguage.EN to "Invoice Number"),
        "creation_date" to mapOf(AppLanguage.AR to "ØªØ§Ø±ÙŠØ® Ø§Ù„Ø¥Ù†Ø´Ø§Ø¡", AppLanguage.EN to "Creation Date"),
        "due_terms" to mapOf(AppLanguage.AR to "Ø´Ø±ÙˆØ· Ø§Ù„Ø¯ÙØ¹", AppLanguage.EN to "Due Terms"),
        "due_date" to mapOf(AppLanguage.AR to "ØªØ§Ø±ÙŠØ® Ø§Ù„Ø§Ø³ØªØ­Ù‚Ø§Ù‚", AppLanguage.EN to "Due Date"),
        "po_number" to mapOf(AppLanguage.AR to "Ø±Ù‚Ù… Ø£Ù…Ø± Ø§Ù„Ø´Ø±Ø§Ø¡ P.O.#", AppLanguage.EN to "P.O.#"),
        "invoice_title_name" to mapOf(AppLanguage.AR to "Ø§Ø³Ù… Ø¹Ù†ÙˆØ§Ù† Ø§Ù„ÙØ§ØªÙˆØ±Ø©", AppLanguage.EN to "Invoice Title Name"),
        "select_template" to mapOf(AppLanguage.AR to "Ø§Ø®ØªØ± Ø§Ù„Ù‚Ø§Ù„Ø¨", AppLanguage.EN to "Select a Template"),
        "export_view_pdf" to mapOf(AppLanguage.AR to "Ø¹Ø±Ø¶ PDF", AppLanguage.EN to "View PDF"),
        "export_saved_downloads" to mapOf(AppLanguage.AR to "ØªÙ… Ø­ÙØ¸ Ø§Ù„Ù…Ù„Ù ÙÙŠ Ø§Ù„ØªÙ†Ø²ÙŠÙ„Ø§Øª", AppLanguage.EN to "File saved in Downloads"),
        "export_send_email" to mapOf(AppLanguage.AR to "Ø¥Ø±Ø³Ø§Ù„ Ø¨Ø§Ù„Ø¨Ø±ÙŠØ¯", AppLanguage.EN to "Send via Email"),
        "export_share_pdf" to mapOf(AppLanguage.AR to "Ù…Ø´Ø§Ø±ÙƒØ© PDF", AppLanguage.EN to "Share PDF"),
        "export_share_text" to mapOf(AppLanguage.AR to "Ù…Ø´Ø§Ø±ÙƒØ© Ø§Ù„Ù†Øµ", AppLanguage.EN to "Share Text"),
        "export_no_app_found" to mapOf(AppLanguage.AR to "Ù„Ø§ ÙŠÙˆØ¬Ø¯ ØªØ·Ø¨ÙŠÙ‚ Ù…Ù†Ø§Ø³Ø¨ Ù„ØªÙ†ÙÙŠØ° Ù‡Ø°Ø§ Ø§Ù„Ø¥Ø¬Ø±Ø§Ø¡", AppLanguage.EN to "No suitable app found to execute this action"),
        "export_error_generic" to mapOf(AppLanguage.AR to "ØªØ¹Ø°Ø± ØªÙ†ÙÙŠØ° Ø§Ù„Ø¥Ø¬Ø±Ø§Ø¡ Ø§Ù„Ø¢Ù†", AppLanguage.EN to "Action cannot be executed now"),
        "doc_detail_invoice" to mapOf(AppLanguage.AR to "ØªÙØ§ØµÙŠÙ„ Ø§Ù„ÙØ§ØªÙˆØ±Ø©", AppLanguage.EN to "Invoice Details"),
        "doc_detail_quote" to mapOf(AppLanguage.AR to "ØªÙØ§ØµÙŠÙ„ Ø¹Ø±Ø¶ Ø§Ù„Ø³Ø¹Ø±", AppLanguage.EN to "Quote Details"),
        "preparing_doc" to mapOf(AppLanguage.AR to "Ø¬Ø§Ø±ÙŠ ØªØ¬Ù‡ÙŠØ² Ø§Ù„Ù…Ø³ØªÙ†Ø¯...", AppLanguage.EN to "Preparing document..."),
        "open_export_options" to mapOf(AppLanguage.AR to "ÙØªØ­ Ø®ÙŠØ§Ø±Ø§Øª Ø§Ù„ØªØµØ¯ÙŠØ±", AppLanguage.EN to "Open Export Options"),
        "error_load_doc_detail" to mapOf(AppLanguage.AR to "ØªØ¹Ø°Ø± ØªØ­Ù…ÙŠÙ„ ØªÙØ§ØµÙŠÙ„ Ø§Ù„Ù…Ø³ØªÙ†Ø¯.", AppLanguage.EN to "Could not load document details."),
        "btn_close" to mapOf(AppLanguage.AR to "Ø¥ØºÙ„Ø§Ù‚", AppLanguage.EN to "Close"),
        "tax" to mapOf(AppLanguage.AR to "Ø§Ù„Ø¶Ø±ÙŠØ¨Ø©", AppLanguage.EN to "Tax"),
        "invoice_terms_cond" to mapOf(AppLanguage.AR to "Ø´Ø±ÙˆØ· ÙˆØ£Ø­ÙƒØ§Ù… Ø§Ù„ÙØ§ØªÙˆØ±Ø©", AppLanguage.EN to "Invoice Terms & Conditions"),
        "selected" to mapOf(AppLanguage.AR to "Ù…Ø­Ø¯Ø¯Ø©", AppLanguage.EN to "Selected"),
        "none" to mapOf(AppLanguage.AR to "Ù„Ø§ ÙŠÙˆØ¬Ø¯", AppLanguage.EN to "None"),
        "invoice_signature" to mapOf(AppLanguage.AR to "ØªÙˆÙ‚ÙŠØ¹ Ø§Ù„Ù…Ø³ØªÙ†Ø¯", AppLanguage.EN to "Invoice Signature"),
        "signed" to mapOf(AppLanguage.AR to "Ù…ÙˆÙ‚Ø¹", AppLanguage.EN to "Signed"),
        "change_template" to mapOf(AppLanguage.AR to "ØªØºÙŠÙŠØ± Ø§Ù„Ù‚Ø§Ù„Ø¨", AppLanguage.EN to "Change Template"),
        "swipe_change_template" to mapOf(AppLanguage.AR to "Ù…Ø±Ø± Ù„Ù„ÙŠÙ…ÙŠÙ† Ø£Ùˆ Ø§Ù„ÙŠØ³Ø§Ø± Ù„Ù„ØªØºÙŠÙŠØ± Ø¨ÙŠÙ† Ø§Ù„Ù‚ÙˆØ§Ù„Ø¨ Ù…Ø¨Ø§Ø´Ø±Ø© Ù…Ø¹ Ø§Ù„Ø¨ÙŠØ§Ù†Ø§Øª Ø§Ù„Ø­Ø§Ù„ÙŠØ©.", AppLanguage.EN to "Swipe left or right to switch templates directly with the current data."),
        "select_currency" to mapOf(AppLanguage.AR to "Ø§Ø®ØªØ± Ø§Ù„Ø¹Ù…Ù„Ø©", AppLanguage.EN to "Select Currency"),
        "local_stored_taxes" to mapOf(AppLanguage.AR to "Ø§Ù„Ø¶Ø±Ø§Ø¦Ø¨ Ø§Ù„Ù…Ø®Ø²Ù†Ø© Ù…Ø­Ù„ÙŠØ§Ù‹", AppLanguage.EN to "Local Stored Taxes"),
        "tax_name" to mapOf(AppLanguage.AR to "Ø§Ø³Ù… Ø§Ù„Ø¶Ø±ÙŠØ¨Ø©", AppLanguage.EN to "Tax Name"),
        "rate_percent" to mapOf(AppLanguage.AR to "Ø§Ù„Ù†Ø³Ø¨Ø© %", AppLanguage.EN to "Rate %"),
        "save_new" to mapOf(AppLanguage.AR to "Ø­ÙØ¸ ÙƒØ¬Ø¯ÙŠØ¯", AppLanguage.EN to "Save New"),
        "no_taxes_stored" to mapOf(AppLanguage.AR to "Ù„Ø§ ØªÙˆØ¬Ø¯ Ø¶Ø±Ø§Ø¦Ø¨ Ù…Ø®Ø²Ù†Ø©", AppLanguage.EN to "No taxes stored"),
        "stored_payment_methods" to mapOf(AppLanguage.AR to "Ø·Ø±Ù‚ Ø§Ù„Ø¯ÙØ¹ Ø§Ù„Ù…Ø®Ø²Ù†Ø©", AppLanguage.EN to "Stored Payment Methods"),
        "new_method_name" to mapOf(AppLanguage.AR to "Ø§Ø³Ù… Ø·Ø±ÙŠÙ‚Ø© Ø§Ù„Ø¯ÙØ¹ Ø§Ù„Ø¬Ø¯ÙŠØ¯Ø©", AppLanguage.EN to "New Method Name"),
        "payment_cash" to mapOf(AppLanguage.AR to "Ù†Ù‚Ø¯ÙŠ", AppLanguage.EN to "Cash"),
        "payment_mada" to mapOf(AppLanguage.AR to "Ù…Ø¯Ù‰", AppLanguage.EN to "Mada"),
        "payment_bank_transfer" to mapOf(AppLanguage.AR to "ØªØ­ÙˆÙŠÙ„ Ø¨Ù†ÙƒÙŠ", AppLanguage.EN to "Bank Transfer"),
        "stored_terms_cond" to mapOf(AppLanguage.AR to "Ø§Ù„Ø´Ø±ÙˆØ· ÙˆØ§Ù„Ø£Ø­ÙƒØ§Ù… Ø§Ù„Ù…Ø®Ø²Ù†Ø©", AppLanguage.EN to "Stored Terms & Conditions"),
        "terms_title" to mapOf(AppLanguage.AR to "Ø§Ù„Ø¹Ù†ÙˆØ§Ù†", AppLanguage.EN to "Title"),
        "terms_content" to mapOf(AppLanguage.AR to "Ù†Øµ Ø§Ù„Ø´Ø±ÙˆØ·", AppLanguage.EN to "Terms Content"),
        "save_new_terms" to mapOf(AppLanguage.AR to "Ø­ÙØ¸ Ø§Ù„Ø´Ø±ÙˆØ· Ø§Ù„Ø¬Ø¯ÙŠØ¯Ø©", AppLanguage.EN to "Save New Terms"),
        "no_terms_stored" to mapOf(AppLanguage.AR to "Ù„Ø§ ØªÙˆØ¬Ø¯ Ù†Ù…Ø§Ø°Ø¬ Ø´Ø±ÙˆØ· Ù…Ø®Ø²Ù†Ø©", AppLanguage.EN to "No terms templates stored"),
        "signatures" to mapOf(AppLanguage.AR to "Ø§Ù„ØªÙˆÙ‚ÙŠØ¹Ø§Øª", AppLanguage.EN to "Signatures"),
        "signature_owner_name" to mapOf(AppLanguage.AR to "Ø§Ø³Ù… ØµØ§Ø­Ø¨ Ø§Ù„ØªÙˆÙ‚ÙŠØ¹", AppLanguage.EN to "Signature Owner Name"),
        "draw_signature_here" to mapOf(AppLanguage.AR to "Ø§Ø±Ø³Ù… ØªÙˆÙ‚ÙŠØ¹Ùƒ Ù‡Ù†Ø§", AppLanguage.EN to "Draw your signature here"),
        "save_signature" to mapOf(AppLanguage.AR to "Ø­ÙØ¸ Ø§Ù„ØªÙˆÙ‚ÙŠØ¹", AppLanguage.EN to "Save Signature"),
        "draw_new_signature" to mapOf(AppLanguage.AR to "Ø±Ø³Ù… ØªÙˆÙ‚ÙŠØ¹ Ø¬Ø¯ÙŠØ¯", AppLanguage.EN to "Draw New Signature"),
        "no_signatures_stored" to mapOf(AppLanguage.AR to "Ù„Ø§ ØªÙˆØ¬Ø¯ ØªÙˆÙ‚ÙŠØ¹Ø§Øª Ù…Ø®Ø²Ù†Ø©", AppLanguage.EN to "No signatures stored"),
        "edit" to mapOf(AppLanguage.AR to "ØªØ¹Ø¯ÙŠÙ„", AppLanguage.EN to "Edit"),
        "no_tax" to mapOf(AppLanguage.AR to "Ø¨Ø¯ÙˆÙ† Ø¶Ø±ÙŠØ¨Ø©", AppLanguage.EN to "No Tax"),
        "final_total" to mapOf(AppLanguage.AR to "Ø§Ù„Ø¥Ø¬Ù…Ø§Ù„ÙŠ Ø§Ù„Ù†Ù‡Ø§Ø¦ÙŠ", AppLanguage.EN to "Final Total"),
        "payment_status" to mapOf(AppLanguage.AR to "Ø­Ø§Ù„Ø© Ø§Ù„Ø¯ÙØ¹", AppLanguage.EN to "Payment Status"),
        "amount_paid" to mapOf(AppLanguage.AR to "Ø§Ù„Ù…Ø¨Ù„Øº Ø§Ù„Ù…Ø¯ÙÙˆØ¹", AppLanguage.EN to "Amount Paid"),
        "additional_invoice_options" to mapOf(AppLanguage.AR to "Ø®ÙŠØ§Ø±Ø§Øª Ø§Ù„ÙØ§ØªÙˆØ±Ø© Ø§Ù„Ø¥Ø¶Ø§ÙÙŠØ©", AppLanguage.EN to "Additional Options"),
        "payment_method" to mapOf(AppLanguage.AR to "Ø·Ø±ÙŠÙ‚Ø© Ø§Ù„Ø¯ÙØ¹", AppLanguage.EN to "Payment Method"),
        "not_specified" to mapOf(AppLanguage.AR to "Ù„Ù… ØªØ­Ø¯Ø¯", AppLanguage.EN to "None"),
        "not_signed" to mapOf(AppLanguage.AR to "Ù„Ù… ÙŠÙˆÙ‚Ø¹", AppLanguage.EN to "None"),
        "terms_cond" to mapOf(AppLanguage.AR to "Ø§Ù„Ø´Ø±ÙˆØ· ÙˆØ§Ù„Ø£Ø­ÙƒØ§Ù…", AppLanguage.EN to "Terms & Conditions"),
        "specified" to mapOf(AppLanguage.AR to "Ù…Ø­Ø¯Ø¯", AppLanguage.EN to "Signed"),
        "template_label" to mapOf(AppLanguage.AR to "Ø§Ù„Ù‚Ø§Ù„Ø¨: %s", AppLanguage.EN to "Template: %s"),
        "app_logo_desc" to mapOf(AppLanguage.AR to "Ø´Ø¹Ø§Ø± Ø§Ù„ØªØ·Ø¨ÙŠÙ‚", AppLanguage.EN to "App Logo"),
        "field_fullname" to mapOf(AppLanguage.AR to "Ø§Ù„Ø§Ø³Ù…", AppLanguage.EN to "Name"),
        "field_store_name" to mapOf(AppLanguage.AR to "Ø§Ø³Ù… Ø§Ù„Ù…ØªØ¬Ø±", AppLanguage.EN to "Store Name"),
        "field_customer_name" to mapOf(AppLanguage.AR to "Ø§Ø³Ù… Ø§Ù„Ø¹Ù…ÙŠÙ„", AppLanguage.EN to "Customer Name"),
        "field_item_name" to mapOf(AppLanguage.AR to "Ø§Ø³Ù… Ø§Ù„Ø¨Ù†Ø¯", AppLanguage.EN to "Item Name"),
        "field_final_tax" to mapOf(AppLanguage.AR to "Ø§Ù„Ø¶Ø±ÙŠØ¨Ø© Ø§Ù„Ù†Ù‡Ø§Ø¦ÙŠØ©", AppLanguage.EN to "Final Tax"),
        "field_price" to mapOf(AppLanguage.AR to "Ø§Ù„Ø³Ø¹Ø±", AppLanguage.EN to "Price"),
        "validation_required" to mapOf(AppLanguage.AR to "%s Ù…Ø·Ù„ÙˆØ¨", AppLanguage.EN to "%s is required"),
        "validation_email_required" to mapOf(AppLanguage.AR to "Ø§Ù„Ø¨Ø±ÙŠØ¯ Ø§Ù„Ø¥Ù„ÙƒØªØ±ÙˆÙ†ÙŠ Ù…Ø·Ù„ÙˆØ¨", AppLanguage.EN to "Email is required"),
        "validation_email_invalid" to mapOf(AppLanguage.AR to "Ø£Ø¯Ø®Ù„ Ø¨Ø±ÙŠØ¯Ù‹Ø§ Ø¥Ù„ÙƒØªØ±ÙˆÙ†ÙŠÙ‹Ø§ ØµØ­ÙŠØ­Ù‹Ø§", AppLanguage.EN to "Enter a valid email address"),
        "validation_password_required" to mapOf(AppLanguage.AR to "ÙƒÙ„Ù…Ø© Ø§Ù„Ù…Ø±ÙˆØ± Ù…Ø·Ù„ÙˆØ¨Ø©", AppLanguage.EN to "Password is required"),
        "validation_password_min_length" to mapOf(AppLanguage.AR to "ÙƒÙ„Ù…Ø© Ø§Ù„Ù…Ø±ÙˆØ± ÙŠØ¬Ø¨ Ø£Ù„Ø§ ØªÙ‚Ù„ Ø¹Ù† 6 Ø£Ø­Ø±Ù", AppLanguage.EN to "Password must be at least 6 characters"),
        "validation_whatsapp_required" to mapOf(AppLanguage.AR to "Ø±Ù‚Ù… ÙˆØ§ØªØ³Ø§Ø¨ Ù…Ø·Ù„ÙˆØ¨", AppLanguage.EN to "WhatsApp number is required"),
        "validation_whatsapp_invalid" to mapOf(AppLanguage.AR to "Ø£Ø¯Ø®Ù„ Ø±Ù‚Ù… ÙˆØ§ØªØ³Ø§Ø¨ ØµØ­ÙŠØ­", AppLanguage.EN to "Enter a valid WhatsApp number"),
        "validation_positive_int" to mapOf(AppLanguage.AR to "%s ÙŠØ¬Ø¨ Ø£Ù† ÙŠÙƒÙˆÙ† Ø±Ù‚Ù…Ù‹Ø§ Ø£ÙƒØ¨Ø± Ù…Ù† ØµÙØ±", AppLanguage.EN to "%s must be a positive integer"),
        "validation_non_negative_int" to mapOf(AppLanguage.AR to "%s ÙŠØ¬Ø¨ Ø£Ù† ÙŠÙƒÙˆÙ† Ø±Ù‚Ù…Ù‹Ø§ ØµØ­ÙŠØ­Ù‹Ø§ ØºÙŠØ± Ø³Ø§Ù„Ø¨", AppLanguage.EN to "%s must be a non-negative integer"),
        "validation_non_negative_money" to mapOf(AppLanguage.AR to "%s ÙŠØ¬Ø¨ Ø£Ù† ÙŠÙƒÙˆÙ† Ø±Ù‚Ù…Ù‹Ø§ ØºÙŠØ± Ø³Ø§Ù„Ø¨", AppLanguage.EN to "%s must be a non-negative number"),
        "error_connect_server" to mapOf(AppLanguage.AR to "ØªØ¹Ø°Ø± Ø§Ù„Ø§ØªØµØ§Ù„ Ø¨Ø§Ù„Ø®Ø§Ø¯Ù…. ÙŠØ±Ø¬Ù‰ Ø§Ù„ØªØ­Ù‚Ù‚ Ù…Ù† Ø§ØªØµØ§Ù„Ùƒ Ø¨Ø§Ù„Ø¥Ù†ØªØ±Ù†Øª.", AppLanguage.EN to "Failed to connect to server. Please check your internet connection."),
        "error_timeout" to mapOf(AppLanguage.AR to "Ø§Ù†ØªÙ‡Øª Ù…Ù‡Ù„Ø© Ø§Ù„Ø§ØªØµØ§Ù„ Ø¨Ø§Ù„Ø®Ø§Ø¯Ù…. ÙŠØ±Ø¬Ù‰ Ø§Ù„Ù…Ø­Ø§ÙˆÙ„Ø© Ù…Ø±Ø© Ø£Ø®Ø±Ù‰.", AppLanguage.EN to "Connection timeout. Please try again."),
        "error_network" to mapOf(AppLanguage.AR to "Ø­Ø¯Ø« Ø®Ø·Ø£ ÙÙŠ Ø§Ù„Ø§ØªØµØ§Ù„ Ø¨Ø§Ù„Ø´Ø¨ÙƒØ©.", AppLanguage.EN to "A network error occurred."),
        "error_invalid_credentials" to mapOf(AppLanguage.AR to "Ø§Ù„Ø¨Ø±ÙŠØ¯ Ø§Ù„Ø¥Ù„ÙƒØªØ±ÙˆÙ†ÙŠ Ø£Ùˆ ÙƒÙ„Ù…Ø© Ø§Ù„Ù…Ø±ÙˆØ± ØºÙŠØ± ØµØ­ÙŠØ­Ø©.", AppLanguage.EN to "Invalid email or password."),
        "error_email_not_registered" to mapOf(AppLanguage.AR to "Ù‡Ø°Ø§ Ø§Ù„Ø¨Ø±ÙŠØ¯ ØºÙŠØ± Ù…Ø³Ø¬Ù„ Ù…Ø³Ø¨Ù‚Ù‹Ø§. ÙŠØ±Ø¬Ù‰ Ø¥Ù†Ø´Ø§Ø¡ Ø­Ø³Ø§Ø¨ Ø£ÙˆÙ„Ù‹Ø§.", AppLanguage.EN to "This email is not registered. Please sign up first."),
        "error_email_not_confirmed" to mapOf(AppLanguage.AR to "Ø§Ù„Ø±Ø¬Ø§Ø¡ ØªØ£ÙƒÙŠØ¯ Ø§Ù„Ø¨Ø±ÙŠØ¯ Ø§Ù„Ø¥Ù„ÙƒØªØ±ÙˆÙ†ÙŠ Ø£ÙˆÙ„Ø§Ù‹.", AppLanguage.EN to "Please confirm your email first."),
        "error_email_already_registered" to mapOf(AppLanguage.AR to "Ø§Ù„Ø¨Ø±ÙŠØ¯ Ø§Ù„Ø¥Ù„ÙƒØªØ±ÙˆÙ†ÙŠ Ù…Ø³Ø¬Ù„ Ø¨Ø§Ù„ÙØ¹Ù„. ÙŠØ±Ø¬Ù‰ ØªØ³Ø¬ÙŠÙ„ Ø§Ù„Ø¯Ø®ÙˆÙ„.", AppLanguage.EN to "This email is already registered. Please sign in."),
        "error_rate_limit" to mapOf(AppLanguage.AR to "ØªÙ… ØªØ¬Ø§ÙˆØ² Ø­Ø¯ Ø¥Ø±Ø³Ø§Ù„ Ø§Ù„Ø±Ù…ÙˆØ². ÙŠØ±Ø¬Ù‰ Ø§Ù„Ù…Ø­Ø§ÙˆÙ„Ø© Ø¨Ø¹Ø¯ Ù‚Ù„ÙŠÙ„.", AppLanguage.EN to "Rate limit exceeded. Please try again in a few moments."),
        "error_invalid_flow_state" to mapOf(AppLanguage.AR to "Ø±Ù…Ø² Ø§Ù„ØªØ­Ù‚Ù‚ ØºÙŠØ± ØµØ­ÙŠØ­ Ø£Ùˆ Ø§Ù†ØªÙ‡Øª ØµÙ„Ø§Ø­ÙŠØªÙ‡.", AppLanguage.EN to "Verification code is invalid or expired."),
        "google_login_error" to mapOf(AppLanguage.AR to "Ø­Ø¯Ø« Ø®Ø·Ø£ Ø£Ø«Ù†Ø§Ø¡ ØªØ³Ø¬ÙŠÙ„ Ø§Ù„Ø¯Ø®ÙˆÙ„ Ø¹Ø¨Ø± Ø¬ÙˆØ¬Ù„. Ø­Ø§ÙˆÙ„ Ù…Ø±Ø© Ø£Ø®Ø±Ù‰.", AppLanguage.EN to "Google sign-in failed. Please try again."),
        "google_login_timeout" to mapOf(AppLanguage.AR to "ØªØ¹Ø°Ø± Ø¥ÙƒÙ…Ø§Ù„ ØªØ³Ø¬ÙŠÙ„ Ø§Ù„Ø¯Ø®ÙˆÙ„ Ø¹Ø¨Ø± Ø¬ÙˆØ¬Ù„. Ø­Ø§ÙˆÙ„ Ù…Ø±Ø© Ø£Ø®Ø±Ù‰.", AppLanguage.EN to "Google sign-in took too long. Please try again."),
        "verification_code_expires_in" to mapOf(AppLanguage.AR to "Ø±Ù…Ø² Ø§Ù„ØªØ­Ù‚Ù‚ ØµØ§Ù„Ø­ Ù„Ù…Ø¯Ø© %d Ø«Ø§Ù†ÙŠØ©.", AppLanguage.EN to "The verification code is valid for %d seconds."),
        "verification_code_expired" to mapOf(AppLanguage.AR to "Ø§Ù†ØªÙ‡Øª ØµÙ„Ø§Ø­ÙŠØ© Ø±Ù…Ø² Ø§Ù„ØªØ­Ù‚Ù‚. Ø§Ø·Ù„Ø¨ Ø±Ù…Ø²Ù‹Ø§ Ø¬Ø¯ÙŠØ¯Ù‹Ø§.", AppLanguage.EN to "The verification code has expired. Request a new one."),
        "verification_code_resent" to mapOf(AppLanguage.AR to "ØªÙ… Ø¥Ø±Ø³Ø§Ù„ Ø±Ù…Ø² ØªØ­Ù‚Ù‚ Ø¬Ø¯ÙŠØ¯.", AppLanguage.EN to "A new verification code has been sent."),
        "resend_code" to mapOf(AppLanguage.AR to "Ø¥Ø¹Ø§Ø¯Ø© Ø¥Ø±Ø³Ø§Ù„ Ø§Ù„Ø±Ù…Ø²", AppLanguage.EN to "Resend code"),
        "resend_code_wait" to mapOf(AppLanguage.AR to "Ø£Ø¹Ø¯ Ø§Ù„Ø¥Ø±Ø³Ø§Ù„ Ø¨Ø¹Ø¯ %d Ø«Ø§Ù†ÙŠØ©", AppLanguage.EN to "Resend in %d seconds"),
        "error_limit_exceeded" to mapOf(AppLanguage.AR to "Ù„Ù‚Ø¯ ØªØ¬Ø§ÙˆØ²Øª Ø§Ù„Ø­Ø¯ Ø§Ù„Ø´Ù‡Ø±ÙŠ Ø§Ù„Ù…Ø³Ù…ÙˆØ­ Ø¨Ù‡ Ù„Ù„Ø¹Ù…Ù„ÙŠØ§Øª.", AppLanguage.EN to "You have exceeded the monthly limit for operations."),
        "error_generic" to mapOf(AppLanguage.AR to "Ø­Ø¯Ø« Ø®Ø·Ø£ ØºÙŠØ± Ù…ØªÙˆÙ‚Ø¹. ÙŠØ±Ø¬Ù‰ Ø§Ù„Ù…Ø­Ø§ÙˆÙ„Ø© Ù„Ø§Ø­Ù‚Ø§Ù‹.", AppLanguage.EN to "An unexpected error occurred. Please try again later."),
        "error_session_expired" to mapOf(AppLanguage.AR to "Ø§Ù†ØªÙ‡Øª ØµÙ„Ø§Ø­ÙŠØ© Ø§Ù„Ø¬Ù„Ø³Ø©. ÙŠØ±Ø¬Ù‰ ØªØ³Ø¬ÙŠÙ„ Ø§Ù„Ø¯Ø®ÙˆÙ„ Ù…Ø±Ø© Ø£Ø®Ø±Ù‰.", AppLanguage.EN to "Session expired. Please log in again."),
        "error_duplicate_customer" to mapOf(AppLanguage.AR to "Ù‡Ø°Ø§ Ø§Ù„Ø¹Ù…ÙŠÙ„ Ù…Ø¶Ø§Ù Ø¨Ø§Ù„ÙØ¹Ù„.", AppLanguage.EN to "This customer is already added."),
        "error_duplicate_product" to mapOf(AppLanguage.AR to "Ù‡Ø°Ø§ Ø§Ù„Ù…Ù†ØªØ¬ Ù…Ø¶Ø§Ù Ø¨Ø§Ù„ÙØ¹Ù„.", AppLanguage.EN to "This product is already added."),
        "error_server" to mapOf(AppLanguage.AR to "Ø­Ø¯Ø« Ø®Ø·Ø£ ÙÙŠ Ø§Ù„Ø®Ø§Ø¯Ù… Ø§Ù„Ø¯Ø§Ø®Ù„ÙŠ.", AppLanguage.EN to "An internal server error occurred."),
        "error_system_with_code" to mapOf(AppLanguage.AR to "Ø­Ø¯Ø« Ø®Ø·Ø£ ÙÙŠ Ø§Ù„Ù†Ø¸Ø§Ù… (%s).", AppLanguage.EN to "A system error occurred (%s)."),
        "error_session_check_failed" to mapOf(AppLanguage.AR to "ÙØ´Ù„ ÙØ­Øµ Ø­Ø§Ù„Ø© Ø§Ù„Ø¬Ù„Ø³Ø©", AppLanguage.EN to "Failed to check session state"),
        "error_after_verification_check" to mapOf(AppLanguage.AR to "Ø­Ø¯Ø« Ø®Ø·Ø£ Ø£Ø«Ù†Ø§Ø¡ ÙØ­Øµ Ø§Ù„Ø¨ÙŠØ§Ù†Ø§Øª Ø¨Ø¹Ø¯ Ø§Ù„ØªØ­Ù‚Ù‚.", AppLanguage.EN to "An error occurred while verifying data."),
        "saudi_arabia" to mapOf(AppLanguage.AR to "Ø§Ù„Ø³Ø¹ÙˆØ¯ÙŠØ©", AppLanguage.EN to "Saudi Arabia"),
    )

    fun getString(key: String, lang: AppLanguage): String {
        return translations[key]?.get(lang) ?: key
    }
}

@Composable
fun t(key: String): String {
    val lang = LocalLanguage.current
    return Localization.getString(key, lang)
}

