package app.tijario.features.documents.template

import app.tijario.features.documents.model.DocumentTemplateDefinition
import app.tijario.features.documents.model.DocumentTemplateVisual

object DocumentTemplateRegistry {
    const val defaultTemplateId: String = "tijario-basic"

    private val legacyAliases = mapOf(
        "basic/teal" to defaultTemplateId,
        "modern/teal" to "tijario-modern",
        "minimal/slate" to "tijario-minimal",
        "compact/teal" to "tijario-compact",
        "corporate/blue" to "tijario-corporate",
        "retail/cyan" to "tijario-retail",
        "elegant/violet" to "tijario-elegant",
        "bold/red" to "tijario-bold",
        "service/green" to "tijario-service",
        "premium/gold" to "tijario-premium",
        "basic/aqua" to "tijario-aqua",
        "service/lime" to "tijario-lime",
        "bold/ruby" to "tijario-ruby",
        "minimal/ink" to "tijario-ink",
        "corporate/blue-band" to "tijario-blue-band",
        "corporate/navy-band" to "tijario-navy-band",
        "premium/gold-band" to "tijario-gold-band",
        "retail/orange-band" to "tijario-orange-band",
        "retail/cyan-band" to "tijario-cyan-band",
        "elegant/violet-band" to "tijario-violet-band",
        "service/forest-band" to "tijario-forest-band",
        "modern/block" to "tijario-block",
        "minimal/outline" to "tijario-outline",
        "premium/slate" to "tijario-slate-cover",
        "premium/emerald" to "tijario-emerald-cover",
        "service/leaf" to "tijario-leaf",
        "tijario-invoice-maker" to defaultTemplateId,
    )

    val templates: List<DocumentTemplateDefinition> = listOf(
        template("tijario-basic", "Tijario Basic", "basic", "teal", "#0F766E", "#0B5F59", "Balanced header, bordered cards, and traditional invoice rhythm."),
        template("tijario-modern", "Tijario Modern", "modern", "teal", "#0B5F59", "#064E3B", "Solid header band and high contrast metadata treatment.", styleFamily = 2, topTextColor = "#FFFFFF", titleTextColor = "#FFFFFF", logoBackgroundColor = "#FFFFFF", logoTextColor = "#0B5F59"),
        template("tijario-minimal", "Tijario Minimal", "minimal", "slate", "#334155", "#1E293B", "Quiet monochrome layout with reduced borders.", styleFamily = 5, titleTextColor = "#111827", tableHeaderTextColor = "#111827", itemTopOuterLine = true, itemBottomBlock = false, itemBottomLine = false),
        template("tijario-compact", "Tijario Compact", "compact", "teal", "#0F766E", "#0B5F59", "Dense layout for documents with many items."),
        template("tijario-corporate", "Tijario Corporate", "corporate", "blue", "#1E40AF", "#1E3A8A", "Structured blue business layout with squared cards.", styleFamily = 2, topTextColor = "#FFFFFF", titleTextColor = "#FFFFFF", logoBackgroundColor = "#FFFFFF", logoTextColor = "#1E40AF"),
        template("tijario-retail", "Tijario Retail", "retail", "cyan", "#0891B2", "#0E7490", "Retail-friendly side accent and alternating item rows.", tableShadeColor = "#ECFEFF"),
        template("tijario-elegant", "Tijario Elegant", "elegant", "violet", "#7C3AED", "#5B21B6", "Centered identity and softer hierarchy for polished quotes.", styleFamily = 3, topTextColor = "#FFFFFF", titleTextColor = "#FFFFFF", logoBackgroundColor = "#FFFFFF", logoTextColor = "#7C3AED", tableShadeColor = "#F3E8FF"),
        template("tijario-bold", "Tijario Bold", "bold", "red", "#B91C1C", "#7F1D1D", "Large title, strong total treatment, and assertive accents.", tableShadeColor = "#FFF1F2", itemTextBold = true),
        template("tijario-service", "Tijario Service", "service", "green", "#15803D", "#166534", "Single-column party treatment for service providers.", tableShadeColor = "#F0FDF4"),
        template("tijario-premium", "Tijario Premium", "premium", "gold", "#92400E", "#78350F", "Premium top rule and warm metadata surfaces.", styleFamily = 6, topTextColor = "#FFFFFF", titleTextColor = "#FFFFFF", logoBackgroundColor = "#FFFFFF", logoTextColor = "#92400E", tableShadeColor = "#FFFBEB", pageAccentColor = "#FFFBEB"),
        referenceTemplate("tijario-aqua", "Tijario Aqua", "basic", "aqua", "#38B7B0", "#0F766E", "Clean teal business document inspired by compact invoice-maker templates."),
        referenceTemplate("tijario-lime", "Tijario Lime", "service", "lime", "#4EAD3A", "#2F6F25", "Fresh green document theme with a simple title led header."),
        referenceTemplate("tijario-ruby", "Tijario Ruby", "bold", "ruby", "#C43A38", "#7F1D1D", "Sharp red accent for urgent invoices and quotations."),
        referenceTemplate("tijario-ink", "Tijario Ink", "minimal", "ink", "#111827", "#020617", "High contrast monochrome document for formal business use.", styleFamily = 5, titleTextColor = "#111827", tableHeaderTextColor = "#111827", itemTopOuterLine = true, itemBottomBlock = false, itemBottomLine = false),
        referenceTemplate("tijario-blue-band", "Tijario Blue Band", "corporate", "blue-band", "#2F6FEF", "#1E3A8A", "Blue header band with boxed metadata.", styleFamily = 2, topTextColor = "#FFFFFF", titleTextColor = "#FFFFFF", logoBackgroundColor = "#FFFFFF", logoTextColor = "#2F6FEF", tableShadeColor = "#EAF1FF"),
        referenceTemplate("tijario-navy-band", "Tijario Navy Band", "corporate", "navy-band", "#20325D", "#111C3A", "Navy professional band for company invoices.", styleFamily = 2, topTextColor = "#FFFFFF", titleTextColor = "#FFFFFF", logoBackgroundColor = "#FFFFFF", logoTextColor = "#20325D", tableShadeColor = "#E8ECF4"),
        referenceTemplate("tijario-gold-band", "Tijario Gold Band", "premium", "gold-band", "#B28A24", "#6F5517", "Warm gold accent with a structured header band.", styleFamily = 2, topTextColor = "#FFFFFF", titleTextColor = "#FFFFFF", logoBackgroundColor = "#FFFFFF", logoTextColor = "#B28A24", tableShadeColor = "#FFF7D6"),
        referenceTemplate("tijario-orange-band", "Tijario Orange Band", "retail", "orange-band", "#E87D2E", "#9A4B12", "Orange header band for retail and service quotes.", styleFamily = 2, topTextColor = "#FFFFFF", titleTextColor = "#FFFFFF", logoBackgroundColor = "#FFFFFF", logoTextColor = "#E87D2E", tableShadeColor = "#FFF1E5"),
        referenceTemplate("tijario-cyan-band", "Tijario Cyan Band", "retail", "cyan-band", "#4A98A5", "#23606B", "Cyan commercial layout with clear table separation.", styleFamily = 2, topTextColor = "#FFFFFF", titleTextColor = "#FFFFFF", logoBackgroundColor = "#FFFFFF", logoTextColor = "#4A98A5", tableShadeColor = "#E7F5F7"),
        referenceTemplate("tijario-violet-band", "Tijario Violet Band", "elegant", "violet-band", "#59428A", "#2F2451", "Violet quote-friendly header with calm metadata cards.", styleFamily = 2, topTextColor = "#FFFFFF", titleTextColor = "#FFFFFF", logoBackgroundColor = "#FFFFFF", logoTextColor = "#59428A", tableShadeColor = "#F0EAFE"),
        referenceTemplate("tijario-forest-band", "Tijario Forest Band", "service", "forest-band", "#2E6B42", "#1A3F28", "Deep green style for service providers and local shops.", styleFamily = 2, topTextColor = "#FFFFFF", titleTextColor = "#FFFFFF", logoBackgroundColor = "#FFFFFF", logoTextColor = "#2E6B42", tableShadeColor = "#EAF7EF"),
        referenceTemplate("tijario-block", "Tijario Block", "modern", "block", "#4D66FF", "#2636A3", "Large title block with strong contrast and clean totals.", styleFamily = 3, topTextColor = "#FFFFFF", titleTextColor = "#FFFFFF", logoBackgroundColor = "#FFFFFF", logoTextColor = "#4D66FF", tableShadeColor = "#EEF1FF"),
        referenceTemplate("tijario-outline", "Tijario Outline", "minimal", "outline", "#111827", "#020617", "Minimal outlined document with unfilled table headers.", styleFamily = 5, titleTextColor = "#111827", tableHeaderTextColor = "#111827", itemTopOuterLine = true, itemBottomBlock = false, itemBottomLine = false),
        referenceTemplate("tijario-slate-cover", "Tijario Slate Cover", "premium", "slate-cover", "#334155", "#0F172A", "Subtle cover-style background accent while preserving A4 readability.", styleFamily = 6, topTextColor = "#FFFFFF", titleTextColor = "#FFFFFF", logoBackgroundColor = "#FFFFFF", logoTextColor = "#334155", tableShadeColor = "#F1F5F9", pageAccentColor = "#EEF2F7"),
        referenceTemplate("tijario-emerald-cover", "Tijario Emerald Cover", "premium", "emerald-cover", "#007041", "#064E3B", "Emerald cover accent for modern retail documents.", styleFamily = 6, topTextColor = "#FFFFFF", titleTextColor = "#FFFFFF", logoBackgroundColor = "#FFFFFF", logoTextColor = "#007041", tableShadeColor = "#E8F7EF", pageAccentColor = "#E8F7EF"),
        referenceTemplate("tijario-leaf", "Tijario Leaf", "service", "leaf", "#12802C", "#0F5F23", "Side-accent document layout inspired by market invoice templates.", styleFamily = 7, titleTextColor = "#FFFFFF", logoBackgroundColor = "#FFFFFF", logoTextColor = "#12802C", tableShadeColor = "#EAF7EF"),
    )

    fun requireTemplate(id: String?): DocumentTemplateDefinition =
        templates.firstOrNull { it.id == normalizeId(id) } ?: templates.first { it.id == defaultTemplateId }

    fun normalizeId(id: String?): String =
        legacyAliases[id] ?: id?.takeIf { templates.any { template -> template.id == it } } ?: defaultTemplateId

    private fun template(
        id: String,
        name: String,
        layoutFamily: String,
        palette: String,
        accentColor: String,
        deepColor: String,
        description: String,
        styleFamily: Int = 1,
        headStyle: Int = 0,
        topTextColor: String = "#2C2D2F",
        titleTextColor: String? = null,
        logoBackgroundColor: String? = null,
        logoTextColor: String = "#FFFFFF",
        tableShadeColor: String = "#F1F5F9",
        tableHeaderTextColor: String = "#FFFFFF",
        itemTopOuterLine: Boolean = false,
        itemBottomBlock: Boolean = true,
        itemBottomLine: Boolean = true,
        itemTextBold: Boolean = false,
        pageAccentColor: String? = null,
    ): DocumentTemplateDefinition =
        DocumentTemplateDefinition(
            id = id,
            name = name,
            version = 2,
            assetDir = "documents/templates/$id",
            family = layoutFamily,
            palette = palette,
            accentColor = accentColor,
            description = description,
            visual = visual(
                styleFamily = styleFamily,
                headStyle = headStyle,
                accentColor = accentColor,
                deepColor = deepColor,
                topTextColor = topTextColor,
                titleTextColor = titleTextColor,
                logoBackgroundColor = logoBackgroundColor,
                logoTextColor = logoTextColor,
                tableShadeColor = tableShadeColor,
                tableHeaderTextColor = tableHeaderTextColor,
                itemTopOuterLine = itemTopOuterLine,
                itemBottomBlock = itemBottomBlock,
                itemBottomLine = itemBottomLine,
                itemTextBold = itemTextBold,
                pageAccentColor = pageAccentColor,
            ),
        )

    private fun referenceTemplate(
        id: String,
        name: String,
        layoutFamily: String,
        palette: String,
        accentColor: String,
        deepColor: String,
        description: String,
        styleFamily: Int = 1,
        headStyle: Int = 0,
        topTextColor: String = "#2C2D2F",
        titleTextColor: String? = null,
        logoBackgroundColor: String? = null,
        logoTextColor: String = "#FFFFFF",
        tableShadeColor: String = "#F1F5F9",
        tableHeaderTextColor: String = "#FFFFFF",
        itemTopOuterLine: Boolean = false,
        itemBottomBlock: Boolean = true,
        itemBottomLine: Boolean = true,
        itemTextBold: Boolean = false,
        pageAccentColor: String? = null,
    ): DocumentTemplateDefinition =
        DocumentTemplateDefinition(
            id = id,
            name = name,
            version = 1,
            assetDir = "documents/templates/tijario-invoice-maker",
            family = layoutFamily,
            palette = palette,
            accentColor = accentColor,
            description = description,
            visual = visual(
                styleFamily = styleFamily,
                headStyle = headStyle,
                accentColor = accentColor,
                deepColor = deepColor,
                topTextColor = topTextColor,
                titleTextColor = titleTextColor,
                logoBackgroundColor = logoBackgroundColor,
                logoTextColor = logoTextColor,
                tableShadeColor = tableShadeColor,
                tableHeaderTextColor = tableHeaderTextColor,
                itemTopOuterLine = itemTopOuterLine,
                itemBottomBlock = itemBottomBlock,
                itemBottomLine = itemBottomLine,
                itemTextBold = itemTextBold,
                pageAccentColor = pageAccentColor,
            ),
        )
    private fun visual(
        styleFamily: Int,
        headStyle: Int,
        accentColor: String,
        deepColor: String,
        topTextColor: String,
        titleTextColor: String?,
        logoBackgroundColor: String?,
        logoTextColor: String,
        tableShadeColor: String,
        tableHeaderTextColor: String,
        itemTopOuterLine: Boolean,
        itemBottomBlock: Boolean,
        itemBottomLine: Boolean,
        itemTextBold: Boolean,
        pageAccentColor: String?,
    ): DocumentTemplateVisual =
        DocumentTemplateVisual(
            styleFamily = styleFamily,
            headStyle = headStyle,
            deepColor = deepColor,
            topTextColor = topTextColor,
            titleTextColor = titleTextColor ?: accentColor,
            logoBackgroundColor = logoBackgroundColor,
            logoTextColor = logoTextColor,
            tableShadeColor = tableShadeColor,
            tableHeaderTextColor = tableHeaderTextColor,
            itemTopOuterLine = itemTopOuterLine,
            itemBottomBlock = itemBottomBlock,
            itemBottomLine = itemBottomLine,
            itemTextBold = itemTextBold,
            pageAccentColor = pageAccentColor,
        )
}
